### ISSUE TITLE
Result always return empty object

### ISSUE THREAD

**Issue by stefensuhat** [geocoder-php/GeocoderLaravel#101]
### General Information
GeocoderLaravel Version: ^4.0
Laravel Version: 5.5.11
PHP Version: 7.2
Operating System and Version: Windows 10

### Description
I have this simple code to try out this package:

`return app('geocoder')->geocode('Los Angeles, CA')->get();`

But everytime it always return me
```
[
{},
{},
{},
{},
{}
]
```

this is my geocoder.php:
```

return [
    'cache-duration' => 0,
    'providers' => [
        Chain::class => [
            GoogleMaps::class => [
                'en-US',
                env('GOOGLE_MAPS_API_KEY'),
            ],
        ],
        GoogleMaps::class => [
            'us',
            env('GOOGLE_MAPS_API_KEY'),
        ],
    ],
    'adapter'  => Client::class,
];
```

All GOOGLE_MAPS_API_KEY already setup. If I run `dd(app('geocoder')->geocode('Los Angeles, CA')->get())` I can see the results. Only when I put return it return me empty.

**Comment by mikebronner** [comment]
Can you paste the method where you are returning the geo coded results? I wonder if the return type is force-typecasting the results? Are you using a return type there?

**Comment by stefensuhat** [comment]
@mikebronner no. my code only `return app('geocoder')->geocode('Los Angeles, CA')->get();` I just want to get the collection result.

I've tried changed the `->get()` to `->first()` it returns me 
`Call to undefined method Geocoder\Laravel\ProviderAndDumperAggregator::first()`

**Comment by mikebronner** [comment]
Please paste the entire method you have your code in.

There is no `first()1st method, you have to do first on the result:
`app('geocoder')-.geocode('...')->get()->first();`

**Comment by stefensuhat** [comment]
@mikebronner only this method i have `return app('geocoder')->geocode('Los Angeles, CA')->get();`

for `first()` method i've just tried to see if it resolve the issue. 

if I dd(app('geocoder')->geocode('Los Angeles, CA')->get()) this is the result: 

```
Collection {#561 ▼
  #items: array:5 [▼
    0 => GoogleAddress {#659 ▼
      -id: "ChIJV_npp981fYcRDwLg180Pemk"
      -locationType: "ROOFTOP"
      -resultType: array:1 [▶]
      -formattedAddress: "13024 SD-244, Keystone, SD 57751, USA"
      -streetAddress: null
      -intersection: null
      -political: "United States"
      -colloquialArea: null
      -ward: null
      -neighborhood: null
      -premise: null
      -subpremise: null
      -naturalFeature: null
      -airport: null
      -park: null
      -pointOfInterest: null
      -establishment: null
      -subLocalityLevels: AdminLevelCollection {#662 ▶}
      -coordinates: Coordinates {#653 ▶}
      -bounds: Bounds {#654 ▶}
      -streetNumber: "13024"
      -streetName: "South Dakota 244"
      -subLocality: null
      -locality: "Keystone"
      -postalCode: "57751"
      -adminLevels: AdminLevelCollection {#660 ▶}
      -country: Country {#658 ▶}
      -timezone: null
      -providedBy: "google_maps"
    }
  ]
}
```

**Comment by mikebronner** [comment]
I am unable to replicate the issue. Unit you can provide me your entire code block, there is not much I can do to help. As previously requested, please provide the entire method that contains your code `return app('geocoder')->geocode('Los Angeles, CA')->get();`. Please review the documentation https://github.com/geocoder-php/Geocoder to see how GeoCoder should be used.

To inspect your results, you can also do this: `return app('geocoder')->geocode('Los Angeles, CA')->get()->toArray();`.

**Comment by stefensuhat** [comment]
@mikebronner what code block do you need? Like I said before, I just tried this package to see if its working or not. and my code only this:

```
Route::get('/', function () {
        $geo = app('geocoder')->reverse(43.882587,-103.454067)->get();
        return $geo;
    });
```

the return result is:
```
[
{},
{},
{},
{},
{}
]
```

I've tried to put `->get()->toArray();` same result.

**Comment by mikebronner** [comment]
A route returns a view or html. It will not render objects. Using `dd()` is the correct way to look at the output.

**Comment by stefensuhat** [comment]
@mikebronner but if you the return statement like what I did, it suppose to return an json object (that's why I cant receive `[{},{}]`. 

I've done this so many times when trying an query or something  else to see if its working or not.

And fyi I've tried to call it via controller with same exact code still return same object.

**Comment by mikebronner** [comment]
The objects in the collection aren't Laravel objects and won't automatically render to JSON. they are normal PHP objects wrapped in a collection.

**Comment by humblecoder** [comment]
So, is there no way to convert an *individual* `Address` object to JSON?  I wouldn't doubt I'm missing something, but returning a collection of PHP objects with no intuitive means of navigation/interpretation doesn't seem helpful.  🤔

**Comment by mikebronner** [comment]
You could always do something like this:

```php
$json = $geocoderResultCollection->map(function ($result) {
        return json_encode($result);
    })
    ->toJson();
```

Let me know how that works.

**Comment by humblecoder** [comment]
@mikebronner Hrm, your method returns an empty set.  I ended up manually building a hash with each function individually (e.g. `getFormattedAddress()`, `getStreetName()`, `getLocality()`)
 😖

**Comment by mikebronner** [comment]
@humblecoder would you mind sharing your solution? perhaps it will help with #132

**Comment by humblecoder** [comment]
Basically I did the following (assumes you're inside a Laravel controller):



Step 1)  Calculate address.

```
$reverse = Geocoder::reverse($request->input('latitude'), $request->input('longitude'))->get();
```

Step 2)  Acquire relevant collection value.  In my case it's the index of the 'ROOFTOP' object.

```
$relevant = $reverse[0]; //JUST IN CASE NOTHING IS FOUND IN THE NEXT STEP

foreach($reverse as $rev){
  if('ROOFTOP' == $rev->getLocationType()){
    $relevant = $rev;
  }
}
```

Step 2)  Call built-in methods on that particular collection value.

```
return response()->json([
  'formatted_address' => $relevant->getFormattedAddress(),
  'street' => ($relevant->getStreetNumber() ?? '') . $relevant->getStreetName(),
  'city' => $relevant->getLocality(),
  'state_province' => $relevant->getAdminLevels()->first()->getName(),
  'postal_code' => $relevant->getPostalCode(),
],200);
```

**Comment by mikebronner** [comment]
@humblecoder Thanks for sharing. This will hopefully help others in the meantime.

The reason for this limitation is that the underlying Geocoder library does not support automatic conversion to json, like eloquent collections do. This package is just a nice wrapper to give standard collections around the objects returned by the Geocoder library.

**Comment by mikebronner** [comment]
@humblecoder @stefensuhat I don't know why I didn't bring this up earlier. You can get the JSON representation via `->dump("geojson")` instead of `->get()`. I added a shortcut in 4.0.21:

```php
app('geocoder')
    ->geocode('1600 Pennsylvania Ave NW, Washington, DC 20500, USA')
    ->toJson();
```

**Comment by dungnh** [comment]
I have same issue as this on Laravel 6.x and PHP 7.3. Please help.

```
$output = app('geocoder')->geocode('Los Angeles, CA')->get();
dd($output);
```
and the result is:

```
Illuminate\Support\Collection {#22243 ▼
  #items: []
}
```

**Comment by luiscolmenares** [comment]
> I have same issue as this on Laravel 6.x and PHP 7.3. Please help.
> 
> ```
> $output = app('geocoder')->geocode('Los Angeles, CA')->get();
> dd($output);
> ```
> 
> and the result is:
> 
> ```
> Illuminate\Support\Collection {#22243 ▼
>   #items: []
> }
> ```

@dungnh try this:
$output = json_decode(app('geocoder')->geocode('Los Angeles, CA')->tojson());

It works as a workaround from what @mikebronner mentioned.

**Comment by omarmfs98** [comment]
I am getting the same answer, please reopen this error

Illuminate\Support\Collection {#457 ▼
  #items: []
}

**Comment by mikebronner** [comment]
@omarmfs98 Please provide the code you are using to get the output. `dd()` and `dump()` will not provide results, as the object contained in the collection don't fall back to an array.
