### ISSUE TITLE
Allow multiple times the same provider in config file.

### ISSUE THREAD

**Issue by JulesPrimo** [geocoder-php/GeocoderLaravel#102]
Ayo,

IDK if issues can be used here for enhancement proposals nor if it php geocoder allows to chain multiple times the same provider (anyway, fairly new into this but didn't read anything that made me think it won't be possible). I use two OSM servers. For now it's one of the two that's used randomly on each thread but the point is not really loadbalancing, it's more about prevention in case of one of them crash.

So I'd like to chain the two of them (maybe a third one, and in theory, as many as I want) and I'll dig into it. Since the config is an array with the FQCN of the provider as a key, it's not possible now.

Just wanna know if it's something that can interest anyone but me, in that case I won't take the quick and dirty way and will do a PR, and if you have any tip about the feasibility of this.

**Comment by mikebronner** [comment]
I think this is something that would need to be explored at the parent package level. In theory you should be able to do this already in the chain provider, as long as you manually configure your geocoding servers within the chain provider to differntiate between them there. If the providers don't provide sufficient configuration optinos, it would be a provider limitation:
- https://github.com/geocoder-php/Geocoder#providers
- https://github.com/geocoder-php/nominatim-provider

Please let me know what you find out, but for now this doesn't appear to be anything we can fix within the laravel package, it seems to be an upstream issue. (This package merely passes on the configuration to whatever providers are being loaded.)

Closing for now, but please do re-open if you find out a solution that requires an update to this package. :) Best of luck!
