### ISSUE TITLE
Getting empty result set

### ISSUE THREAD

**Issue by Norgul** [geocoder-php/GeocoderLaravel#111]
### General Information
GeocoderLaravel Version: 4.0
Laravel Version: 5.5
PHP Version: 7.0.0.
Operating System and Version: MacOS High Sierra

### Issue Description

I am getting an empty array no matter what I do with the package. I have installed it through Composer and added to `app.php`

    Geocoder\Laravel\Providers\GeocoderService::class,

Published the config, which is located in `geocoder.php`

```
use Geocoder\Provider\Chain\Chain;
use Geocoder\Provider\GeoPlugin\GeoPlugin;
use Geocoder\Provider\GoogleMaps\GoogleMaps;
use Http\Client\Curl\Client;

return [
    'cache-duration' => 9999999,
    'providers' => [
        Chain::class => [
            GoogleMaps::class => [
                'en-US',
                env('GOOGLE_MAPS_API_KEY'),
            ],
            GeoPlugin::class  => [],
        ],
    ],
    'adapter'  => Client::class,
];
```

And added Google API key to my `.env` file under `GOOGLE_MAPS_API_KEY` name.

First I tried with 

`return Geocoder::geocode(request()->ip())->get();`

But that returned `[]`. After that I went to check the documentation again and used the example from there:

`return app('geocoder')->geocode('Los Angeles, CA')->get();`

I also tried:

`return app('geocoder')->geocode('Los Angeles, CA')->get(1);`
`return app('geocoder')->geocode('Los Angeles, CA')->all();`

But again nothing. What may be the issue?

I cleared the composer and artisan cache, and ran `composer dump-autoload` also. Same issue

**Comment by mikebronner** [comment]
Hi @Norgul, For Laravel 5.5 it is important NOT to register the provider manually. That might be causing the issue. Please remove the provider from `config/app.php` and try again and let me know how that goes.

Also, try using the default config first, before publishing the config. Go ahead and delete the published config file and try again.

Let me know how those go, and we'll go from there.

**Comment by Norgul** [comment]
I thought only alias was automatically registered. Anyway, I removed the provider and ran `composer dump-autoload`. Also deleted the config file. Same thing happens

**Comment by mikebronner** [comment]
OK, lets try running the unit tests next. SSH into Laravel Homestead, and go to your project folder. Then type the following:
```sh
cd vendor/toin0u/geocoder-laravel
composer install
vendor/bin/phpunit
```

Please run the tests a few times if you get errors, as some of the services block access temporarily from local dev environments. If you get consistent errors, please paste them here.

**Comment by mikebronner** [comment]
Also, please make sure to clear you cache and try again.
```sh
php artisan cache:clear
```

**Comment by Norgul** [comment]
I think that Mockery failed composer installation for some reason, and when I repeat the process it says there is nothing to install or update.

When I ran the tests, every test failed, but I don't see how it should pass if Mockery isn't installed.

The "readable" errors I could see were something like:

```
vendor/toin0u/geocoder-laravel/tests/Laravel5_5/Providers/GeocoderServiceTest.php:26

Caused by
PDOException: could not find driver
```

```
vendor/toin0u/geocoder-laravel/tests/Laravel5_5/Providers/GeocoderServiceTest.php:26

Caused by
Doctrine\DBAL\Driver\PDOException: could not find driver
```

```
9) Geocoder\Laravel\Tests\Laravel5_5\Providers\GeocoderServiceTest::testConfig
Illuminate\Database\QueryException: could not find driver (SQL: select * from sqlite_master where type = 'table' and name = migrations)
```

**Comment by Norgul** [comment]
I tried deleting the vendor file and doing `composer install` again after clearing composer cache, and now even more failed packages

<img width="883" alt="screenshot at dec 07 22-00-31" src="https://user-images.githubusercontent.com/11718157/33738642-2983b62e-db9a-11e7-9d99-582dbd9e3a5f.png">

**Comment by mikebronner** [comment]
It looks like you might have some internet connectivity issues, or perhaps ISP issues, which might be causing your lookups to fail. At this point I don't see anything that points to the package causing the problem.

**Comment by Norgul** [comment]
Oh, actually now I see that below that it says Downloading 100%...so it is downloading it after all.

**Comment by Norgul** [comment]
I ran the tests again, this is the first one on the list

```
EEEEEEEEEEEEEEEEEEEEEEEEEE                                        26 / 26 (100%)

Time: 2.6 seconds, Memory: 22.00MB

There were 26 errors:

1) Geocoder\Laravel\Tests\Laravel5_5\Providers\GeocoderServiceTest::testItReverseGeocodesCoordinates
Illuminate\Database\QueryException: could not find driver (SQL: select * from sqlite_master where type = 'table' and name = migrations)

```

**Comment by Norgul** [comment]
Also if I try to do this:

`return \Geocoder::geocode('Los Angeles, CA')->all();`

I get the error response that class Geocoder is not found? How is that possible if it registers it automatically?

**Comment by Norgul** [comment]
I also tried diving into the code and dumping `$this->aggregator->getProviders()` and I am only getting back 

```
{
    "chain": {}
}
```

Is that the problem? Why isn't GoogleMaps registered?

**Comment by Norgul** [comment]
Is Google maps API key mandatory? I suppose it is, I tried with JS API key, and embed API key, and with no key at all. Same result

**Comment by mikebronner** [comment]
Sorry @Norgul at this point it looks more like something with your project, implementation, configuration, or development environment. :(
Please try an a fresh Laravel project and make sure GeocoderLaravel is up-to-date.

**Comment by Norgul** [comment]
I tried the fresh installation also, and I get the same result.

Could you confirm two things:
1. Geocoder works within vagrant virtual box?
2. Geocoder needs Google maps API key?  (if yes, which one? Javascript one?)

**Comment by mikebronner** [comment]
1.  It works in Laravel Homestead -- I cannot guarantee it works in any other flavor of vagrant box.
2. Yes, I believe it's the javascript one. Please consult the documentation for the parent project as to the exact requirements: https://github.com/geocoder-php/Geocoder.

**Comment by Norgul** [comment]
I tried using Google Geocoding API key instead of Google Maps one (since that says under original repository, tests section) but still nothing. 

Installing fresh Laravel app even on another machine (Win 10), even with new homestead, returns empty set. Clearing all cache didn't help either. Running Chrome in incognito didn't help.

One thing I noticed in the documentation was saying to set HTTPS to true, but I didn't see that option anywhere?

**Comment by Norgul** [comment]
Nope, it's a business private app, but I can put the test repo up...even though I'm not sure what may be the issue or what may be different as I am doing things this way:

1. laravel new some_project
2. installing package through composer
3. provisioning vagrant, clearing cache
4. adding ENV google API key
5. test
6. fail

**Comment by mikebronner** [comment]
OK, post up a test project repo, and I will try to replicate the problem. If it works on my end, it is an environmental issue in your dev environment. If its a code issue I should be able to see it.

**Comment by Norgul** [comment]
[Repo](https://github.com/Norgul/test)

There, you can check it out. Thanks

**Comment by IceDann** [comment]
What does Google maps return on the URL this package tries to address?
Had the same issue what you describe and came to the conclusion that Google Maps refused to send me the results.

**Comment by Norgul** [comment]
You mean this?

    const GEOCODE_ENDPOINT_URL_SSL = 'https://maps.googleapis.com/maps/api/geocode/json?address=%s';

When I replace the address and paste this to browser I get the results back.

**Comment by Norgul** [comment]
I think you should change the documentation, and on top of that maybe even the code as it is somewhat unclear now.

First, Google API key is not mandatory. 

After I did `dd(app('geocoder')->geocode('5.43.168.58')->get())` I am infact getting the results back. But saying that it is working as a Laravel collection is I think not true as once again, if I don't die and dump, I see nothing. 

Where I'd expect to do `app('geocoder')->geocode('5.43.168.58')->get()->country` to fetch country from geocoded result, I actually need to do this:

    app('geocoder')->geocode('5.43.168.58')->get()->first()->getCountry()->getName();

This by itself looks in my opinion a bit too complex, but even with that in mind, I'd get to it somehow if I got the dump back on my screen with the simple `get()`

You can consider this issue closed. Thank you for the time

**Comment by mikebronner** [comment]
@Norgul the result you get is a true Laravel Collection consisting of results. You need to operate on each individually as you would otherwise if it weren't a laravel collection. But because it is a laravel collection, you can manipulate it with all the accustomed Collection methods.

Glad to see you have it working.

**Comment by Norgul** [comment]
I'm just referring to what the package had for Laravel 4.2 version. It was like this

    Geocoder::geocode('0.0.0.0')->getCity()

Seems like a much cleaner solution in my opinion

**Comment by mikebronner** [comment]
It has since been completely overhauled. If you want a more bare-bones implementation, you might consider just pulling in the parent package instead of this one.

**Comment by Norgul** [comment]
I won't get in the reasons of overhaul nor how you meant the package the function. I would just for the sake of users like myself recommend for a bit more details in the documentation about how to actually get the data :)

**Comment by andreshg112** [comment]
Same problem here, but with reverse():
![image](https://user-images.githubusercontent.com/15859884/42742252-11803dbc-887f-11e8-9543-587502b09854.png)

But if I do this with geocode(), It works:
![image](https://user-images.githubusercontent.com/15859884/42742276-352bd4c4-887f-11e8-8761-983b9cc36773.png)

**Comment by andreshg112** [comment]
Sorry, I got problems with my API Key. But, I suggest you show or throw an error instead of empty results.

**Comment by brentscholl** [comment]
I'm having the same problem with `reverse()` returning empty.

How did you solve this issue regarding API key?

**Comment by andreshg112** [comment]
Hi, @brentscholl !
I think I did: `dd(app('geocoder')->reverse('10.5', '-75.2'));`, then I search for the URL and I click on it. I could see the error in the browser. I had to create a new API.

**Comment by brentscholl** [comment]
Thanks for the response!

Hmm. Ok the big difference is `dd(app('geocoder')->reverse('10.5', '-75.2'))` returns a result.  I found the URL. When I click on it, it returns the JSON results.

But `dd(app('geocoder')->reverse('10.5', '-75.2')->get())` returns `null`

I'm having an issue where I can not use `getStreetName()` or `getCountry()` etc.

`dd(app('geocoder')->reverse('10.5', '-75.2')->get()->first()->getCountry());`
returns **Call to a member function getCountry() on null**

Am I doing something wrong?

**Comment by andreshg112** [comment]
`app('geocoder')->reverse('10.5', '-75.2')->get();` should return a Collection. If it doesn't, it's not working.
This worked for me:
![image](https://user-images.githubusercontent.com/15859884/43499320-8e012dea-9510-11e8-9bef-107ddb08fa7f.png)

Can you show us your JSON result?
It has to look like this:
![image](https://user-images.githubusercontent.com/15859884/43499299-798395c4-9510-11e8-93ee-e92d9dbdd5e7.png)

**Comment by brentscholl** [comment]
When I visit the URL `https://maps.googleapis.com/maps/api/geocode/json?latlng=52.773613,-108.297923&region=en-US&key=[MY API KEY HERE]`

I get this:
![json](https://user-images.githubusercontent.com/30605668/43499585-886e3992-9509-11e8-9fad-48c072ab89b2.jpg)



`dd(app('geocoder')->reverse('52.7737667', '-108.2977717'));`

Gives me an empty collection
![screencapture-127-0-0-1-8080-register-2018-07-31-21_34_00](https://user-images.githubusercontent.com/30605668/43499598-9c2a8170-9509-11e8-9875-33afac6eba93.png)

**Comment by andreshg112** [comment]
Could you try with `use Geocoder\Laravel\Facades\Geocoder;` instead of `app('geocoder')`.

Do you see something strange when you do: `dd(Geocoder::reverse($this->latitude, $this->longitude))`?

**Comment by brentscholl** [comment]
I tried what you suggest. Just the same result.

**Comment by andreshg112** [comment]
config/geocoder.php:
```php
<?php

use Geocoder\Provider\Chain\Chain;
use Geocoder\Provider\GeoPlugin\GeoPlugin;
use Geocoder\Provider\GoogleMaps\GoogleMaps;
use Http\Client\Curl\Client;

return [
    'cache' => [

        /*
        |-----------------------------------------------------------------------
        | Cache Store
        |-----------------------------------------------------------------------
        |
        | Specify the cache store to use for caching. The value "null" will use
        | the default cache store specified in /config/cache.php file.
        |
        | Default: null
        |
        */

        'store' => null,

        /*
        |-----------------------------------------------------------------------
        | Cache Duration
        |-----------------------------------------------------------------------
        |
        | Specify the cache duration in minutes. The default approximates a
        | "forever" cache, but there are certain issues with Laravel's forever
        | caching methods that prevent us from using them in this project.
        |
        | Default: 9999999 (integer)
        |
        */

        'duration' => 9999999,
    ],

    /*
    |---------------------------------------------------------------------------
    | Providers
    |---------------------------------------------------------------------------
    |
    | Here you may specify any number of providers that should be used to
    | perform geocaching operations. The `chain` provider is special,
    | in that it can contain multiple providers that will be run in
    | the sequence listed, should the previous provider fail. By
    | default the first provider listed will be used, but you
    | can explicitly call subsequently listed providers by
    | alias: `app('geocoder')->using('google_maps')`.
    |
    | Please consult the official Geocoder documentation for more info.
    | https://github.com/geocoder-php/Geocoder#providers
    |
    */
    'providers' => [
        Chain::class => [
            GoogleMaps::class => [
                env('GOOGLE_MAPS_LOCALE', 'en-US'),
                env('GOOGLE_MAPS_API_KEY'),
            ],
            GeoPlugin::class  => [],
        ],
    ],

    /*
    |---------------------------------------------------------------------------
    | Adapter
    |---------------------------------------------------------------------------
    |
    | You can specify which PSR-7-compliant HTTP adapter you would like to use.
    | There are multiple options at your disposal: CURL, Guzzle, and others.
    |
    | Please consult the official Geocoder documentation for more info.
    | https://github.com/geocoder-php/Geocoder#usage
    |
    | Default: Client::class (FQCN for CURL adapter)
    |
    */
    'adapter'  => Client::class,

    /*
    |---------------------------------------------------------------------------
    | Reader
    |---------------------------------------------------------------------------
    |
    | You can specify a reader for specific providers, like GeoIp2, which
    | connect to a local file-database. The reader should be set to an
    | instance of the required reader class.
    |
    | Please consult the official Geocoder documentation for more info.
    | https://github.com/geocoder-php/geoip2-provider
    |
    | Default: null
    |
    */
    'reader' => null,

];

```

.env:
```env
GOOGLE_MAPS_LOCALE=es
GOOGLE_MAPS_API_KEY=xxx
```

**Comment by andreshg112** [comment]
Have you tried `php artisan cache:clear`?

**Comment by brentscholl** [comment]
My `config/geocoder.php` is same as yours. and yes tried `php artisan cache:clear` same result. I have also done everything Norgul has done. 

(also, see my edit answer above for JSON)

**Comment by brentscholl** [comment]
`dd(app('geocoder')->geocode('5.43.168.58')->get()->first()->getCountry()->getName());` works fine. It is only a problem when I use `reverse()` so I feel like my config is all fine? I'm not sure what I'm missing. I'm not using a virtual box, my project is local using `php artisan serve`

**Comment by andreshg112** [comment]
`geocode()` almost always works because It doesn't use google maps or any API key. I use Lampp (Xampp). Have you tried stopping your firewall for a moment?

**Comment by brentscholl** [comment]
Just tried. Getting same results. Empty Collection
