### ISSUE TITLE
How to use Nominatim to get bounds of a city?

### ISSUE THREAD

**Issue by g5400658** [geocoder-php/GeocoderLaravel#115]
I'm trying to get the boundary coordinates of a city. For example, I want to get the Southwest and Northeast coordinates like so:

https://i.imgur.com/6Qn7wPn.png

I found that if I go to the URL below, it returns a `boundingbox` property, with the coordinates I'm looking for:

https://nominatim.openstreetmap.org/search?q=mississauga,on&format=json

How can I use this library to fetch the boundary coordinates of a city?

I updated my config like so:

```
    'providers' => [
        Chain::class => [
            Nominatim::class => [
                env('GOOGLE_MAPS_LOCALE', 'en-US'),
                env('GOOGLE_MAPS_API_KEY'),
            ],
        ],
    ],
```

However, I don't think my config is correct (what values should I put in the provider array?), because when I run this code:

```
app('geocoder')->geocode('Mississauga')->dump('geojson');
```

It returns no result:

```
[

]
```

What am I doing wrong?

**Comment by mikebronner** [comment]
Are you getting results with other providers? Also, depending on your development environment, there may be an issue with OpenSSL not being updated.

Have you referenced the documentation: https://github.com/geocoder-php/Geocoder#providers

https://github.com/geocoder-php/Geocoder/search?utf8=✓&q=getbounds&type=

you should be able to use `->getBounds()` to get the bounds off a single result:
```php
$results = app('geocoder')->geocode('Mississauga');

foreach ($results as $result) {
    dd($result->getBounds());
}
```

**Comment by g5400658** [comment]
Hi,

Yes, I'm getting results if I use Google Maps API. 

Is my config correct? Or should the values be different?

**Comment by mikebronner** [comment]
I honestly have no idea ... I would open an issue here https://github.com/geocoder-php/nominatim-provider

I have never used Nominatim, and this package is just an elaborate Laravel wrapper for the GeocoderPhp project. :) If you are able to figure it out there, please do let me know.

**Comment by jmichaelterenin** [comment]
Nominatim::class => [
                root-url,
                language-locale,
            ],

where root-url is: "https://nominatim.openstreetmap.org"
and language-locale (for me) is: "en"

Just open up the constructor for the Adapter you want to use and you'll see what parameters are required/optional.
