### ISSUE TITLE
GeoIP2 provider with GoogleMaps provider

### ISSUE THREAD

**Issue by Norgul** [geocoder-php/GeocoderLaravel#116]
### General Information
GeocoderLaravel Version: 4.0
Laravel Version: 5.5
PHP Version: 7.1
Operating System and Version: MacOS Sierra

### Issue Description
I wanted to use multiple providers as specified in documentation. Specifically I wanted to use [GeoIP2](https://packagist.org/packages/geocoder-php/geoip2-provider) provider along side Google maps one. 

I checked out the issue #4 but it doesn't answer my question really. Is registration of multiple providers possible using only published config file?

I tried this:

```
'providers' => [
    Chain::class => [
        \Geocoder\Provider\GeoIP2\GeoIP2::class => [],
        GoogleMaps::class => [
            env('GOOGLE_MAPS_LOCALE', 'en-US'),
            env('GOOGLE_MAPS_API_KEY'),
        ],
        GeoPlugin::class  => [],
    ],
],
```

And after errors about adapters, I also modified an adapter:

    'adapter'  => \Geocoder\Provider\GeoIP2\GeoIP2Adapter::class,

But I am getting an error

> Type error: Argument 1 passed to Geocoder\Provider\GeoIP2\GeoIP2Adapter::__construct() must be an instance of GeoIp2\ProviderInterface, none given, called in /home/.../vendor/toin0u/geocoder-laravel/src/ProviderAndDumperAggregator.php on line 231

**Comment by mikebronner** [comment]
Hi @Norgul,

Thanks for reaching out with your specific use-case.

To answer your first question: yes, anytime you want to change which providers or adapters are loaded, you would need to publish the config and customize it. So you're on the right path there.

As to the second part of the issue, let me look into what's happening there and make sure the provider works. I'll get back to you hopefully later today.

**Comment by mikebronner** [comment]
@Norgul Don't change the adapter in the config file. I already account for that when registering the providers. Can you post the error message you get without changing the adapter in the config file?

**Comment by mikebronner** [comment]
@Norgul I have made some changes to how GeoIP2 is loaded. Please review the updated config in the readme. To get an idea of how to set up GeoIP2, take a look at the test configuration: https://github.com/geocoder-php/GeocoderLaravel/blob/1da707448510dbcfea30c41c1d521b28271cb72c/tests/config/testConfig.php#L39

Let me know if this works for you! :) Thanks for reporting the problem.

**Comment by Norgul** [comment]
Also while you're at it...can you tell me whether it is possible to have multiple adapters also?

**Comment by Norgul** [comment]
Hi @mikebronner thank you for the info, I updated the package with `composer update` and inserted DB I have in the reader under the config, however I am still getting the same error. I presume it is possibly because the `GeoIP2Adapter` in constructor takes 

    public function __construct(ProviderInterface $geoIpProvider, $geoIP2Model = self::GEOIP2_MODEL_CITY)

and it doesn't get automatically resolved on runtime. 

I'm a little puzzled about the whole adapter thing, I know that it is supposed to somehow help provider do its job, but I'm still not sure if one adapter can work for more providers? For example if I use this provider now and somehow make it function, will my Google maps provider fail?

On that subject, is it possible to use more than one adapter and/or map it somehow to a provider?

**Comment by mikebronner** [comment]
Hi @Norgul, please provide your complete configuration file, the line of code that is causing the error, and the complete error stack trace.
You can only use a single adapter, however, GeocoderLaravel will handle the adapter GeoIP2 for you, so you want to leave the adapter using an HTTP adapter, so that the chain provider will work.

The first provider in the configuration file will be the default provider used. To access subsequent providers you need to specify them in your lookup;
```php
app('geocoder')->geocode('address')->using('provider")->get();
```

The chain provider will go through each provider it contains until it finds a result.

**Comment by mdupor** [comment]
I tried reinstalling all the packages needed, also updated `composer require php-http/curl-client` and now it works. Thanks!

The provider however doesn't fetch a `locality()` but it founds country (actually, nothing but country and coordinates is found). Is that the DB issue then or?

**Comment by Norgul** [comment]
I tried reinstalling all the packages needed, also updated `composer require php-http/curl-client` and now it works. Thanks!

The provider however doesn't fetch a `locality()` but it founds country (actually, nothing but country and coordinates is found). Is that the DB issue then or?

**Comment by mikebronner** [comment]
@Norgul yes, that sounds like an issue specific to the database you have connected. It may not contain any other information. You would have to check with whomever supplied the database to you. Glad you got things working! :)
