### ISSUE TITLE
The project doesn't need to use Testbench BrowserKit

### ISSUE THREAD

**Issue by crynobone** [geocoder-php/GeocoderLaravel#121]
From what I see in the tests folder, you don't actually need Testbench BrowserKit, `FeatureTestCase` should just extends `Orchestra\Testbench\TestCase`.

### Testbench

It's loads Laravel apps and able you to run artisan commands, migrations, basic routing from within your tests.

### Testbench BrowserKit

It extends **Testbench** an allow you to interact with the view using CSS selectors (interacting with form, button, link etc) but without JavaScript.

### Testbench Dusk

It extends **Testbench** an allow you to interact with the view using CSS selectors (interacting with form, button, link etc) with JavaScript (using Chrome browser).

**Comment by mikebronner** [comment]
Right, I know they aren't necessary. My dev workflow includes this encompassing setup. I have moved to this for all my packages, and like to keep the same workflow for all packages for maintenance and ease of use. :)

But you're right, the existing tests don't utilize any browser actions, and should just extend Testbench.
