### ISSUE TITLE
PHP 7.0

### ISSUE THREAD

**Issue by dneykov** [geocoder-php/GeocoderLaravel#122]
Is this library compatible with PHP Version 7.0.24

Thanks.

**Comment by mikebronner** [comment]
It may work, however, I have not tested it against that. If you are using Laravel 5.6 you will definitely need to use PHP 7.1.3 or higher. If it's not compatible you would get an exception. Hardly anything changed in the package when we added L5.6 compatibility, so you should be ok, but I can't guarantee it.
