### ISSUE TITLE
Support for Lumen

### ISSUE THREAD

**Issue by cg-rsands** [geocoder-php/GeocoderLaravel#124]
### General Information
GeocoderLaravel Version: 4.0.6
Laravel Version: **Lumen** 5.6
PHP Version:  7.1

### Issue Description
config_path() is not present in lumen, undefined function

### Steps to Replicate
Install package and add service provider

**Comment by cg-rsands** [comment]
Side note.  Tinker had this issue and the fix they implemented was here:

https://github.com/laravel/tinker/commit/4cdc9c35744de929272f0b7245669e7520b486ce

**Comment by mikebronner** [comment]
Thanks for the update :) Will take a look at this over the weekend. :)

**Comment by mikebronner** [comment]
@cg-rsands Could you test version 4.0.8 if that fixes the issue? I don't have Lumen installed to test on.

Thanks!
