### ISSUE TITLE
How to use google maps for business

### ISSUE THREAD

**Issue by Jaume007** [geocoder-php/GeocoderLaravel#127]
### General Information
GeocoderLaravel Version: 4.0
Laravel Version: 5.4
PHP Version: 7.0

### Issue Description
We have an application that relies heavily on geocoding addresses and drawing routes. Mainly our queries to google maps are done from frontend but we need to geocode some addresses from our api. We have a google business account for google maps.
I'm trying to set up the GoogleMaps provider to use our Google business account but I don't know how to set it up.
I see in the GoogleMaps provider in line 82 the method business, but I don't know hot to make the packet use that.

Any help would be greatly apreciated

**Comment by mikebronner** [comment]
@Jaume007 Unfortunatly I don't have the answer to that as I have not used Google Maps for Business. Also, specific GeoCoder functionality is probably better asked in the parent repo: https://github.com/geocoder-php/Geocoder. You will probably have better luck there. :) Sorry for not being able to help at this time.
