### ISSUE TITLE
Suggestion: Locale as config variable

### ISSUE THREAD

**Issue by sololance** [geocoder-php/GeocoderLaravel#128]
### General Information
GeocoderLaravel Version: latest
Laravel Version: 5.6
PHP Version: 7.2.16
Operating System and Version: ubuntu

### Issue Description
When having multiple providers we need to set language value "withLocale" variable. Provider may have different language settings and it's easy to forget which one had variable set.

What I suggest adding easy method to set this variable "withLocale" in this library too if possible?

### Steps to Replicate
Best example would be Yandex. Yandex doesn't have language variable in construct method and only possible way to set response language is:

`$query = ReverseQuery::fromCoordinates(43.882587,-103.454067)->withLocale($lang);`

`$results = app('geocoder')->reverseQuery($query)->get();`

Also the main problem I had is setting up language for Google Maps.

**Comment by mikebronner** [comment]
@sololance  I'll look into this, thanks!

**Comment by mikebronner** [comment]
See the examples here how to set locale: https://github.com/geocoder-php/Geocoder#statefulgeocoder
I don't think this package should differ from the parent implementation. Let me know if that doesn't work for some reason, I'll close this issue in the meanwhile. Thanks! :)
