### ISSUE TITLE
How do it test it

### ISSUE THREAD

**Issue by osc2nuke** [geocoder-php/GeocoderLaravel#133]
Where is the link to check my location?

**Comment by mikebronner** [comment]
Please elaborate -- check your location against what -- check your location how -- which link are you expecting?

This package converts addresses (postal, IP) to lats and longs, commonly known as geocoding.

**Comment by osc2nuke** [comment]
Just show me that what is offered works.
I visit your site based on the current package.
You even make a website for it.
Yet there is NOTHING to determine my real geolocation.
So how you offer me to use your package, so i can actually see it works?

**Comment by osc2nuke** [comment]
There is to many packages out there,
You think i gonna split each of them?
I not want to waste my time of non working resources.

**Comment by mikebronner** [comment]
@osc2nuke you are free to try out the package and see if it works, if it doesn't do what you need, try another package. Please keep in mind that this is a FREE open-source package, and we only have limited resources to devote to it. To read up on the documentation as to what this package offers, please review the following: 
- https://github.com/geocoder-php/Geocoder/blob/master/README.md
- https://github.com/geocoder-php/GeocoderLaravel/blob/master/README.md

Almost everything is documented. I am closing this issue as this really boils down to you doing your homework on packages you want to use. We can't do that for you.

**Comment by osc2nuke** [comment]
Not claim what you not can offer.

**Comment by mikebronner** [comment]
We are not wasting anyone's time. Feel free to choose another package that doesn't "waste your time". We make this package available as-is and are open to questions, and do our best to help. However, we cannot research which packages work for your specific situation and project, that is only something you can do.
