### ISSUE TITLE
No provider could provide the address Error

### ISSUE THREAD

**Issue by bartmoons** [geocoder-php/GeocoderLaravel#14]
I edited my config file to

```
return array(
   'providers' => array(
       'Geocoder\Provider\GoogleMapsProvider' => array('en_EN', null),
       'Geocoder\Provider\FreeGeoIpProvider'  => null,
    ),
'adapter'  => 'Geocoder\HttpAdapter\CurlHttpAdapter'
);
```

On my local server it's working fine, but once I try it online I get the

```
No provider could provide the address "Moscow, Russia"
```

I also tried ('en_EN', 'English', $ssl = true, 'xxxxxxxxxxxxxx api-key xxxxxxx'), but that didn't work either.
Any ideas?

**Comment by ferrysutanto19** [comment]
guys, i have the same error too.
i just followed the basic tutorial
and it says "No provider could provide the address "10 rue Gambetta, Paris, France".

fyi, i'm using xampp with php 5.6
laravel 5.0

**Comment by 1moere1** [comment]
same problem as ferrysutanto19 has

**Comment by fabioi** [comment]
+1

**Comment by fabioi** [comment]
Hi, just a note, following the example here https://github.com/geocoder-php/GeocoderLaravel/issues/9 I made it work.

###geocoder.php 
```php
<?php

/**
 * This file is part of the GeocoderLaravel library.
 *
 * (c) Antoine Corcy <contact@sbin.dk>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

return [
    // Providers get called in the chain order given here.
    // The first one to return a result will be used.
    'providers' => [
//        'Geocoder\Provider\GoogleMapsProvider' => ['fr-FR', 'Île-de-France', true],
        'Geocoder\Provider\GoogleMapsProvider' => ['it-IT', 'Italia', true],
        'Geocoder\Provider\FreeGeoIpProvider'  => null,
    ],
    'adapter'  => 'Geocoder\HttpAdapter\CurlHttpAdapter',
];

```
###the file where you perform the geocoding
```php
$adapter = App::make('geocoder.adapter');
        $providers = array(
            new \Geocoder\Provider\GoogleMapsProvider($adapter, env('GOOGLE-API-KEY')),
        );

        try {
            // maybe the chain provider is better here :)
            Geocoder::registerProviders($providers);
            Geocoder::using('GoogleMapsProvider');
            $geocode = Geocoder::geocode('Via Corsica 7, Brescia, Italy');
            var_dump($geocode);
        } catch (\Exception $e) {
            echo $e->getMessage();
        }

```

Hope it helps,

Fabio

**Comment by kallyssi** [comment]
hi,
i am getting the same issue in my local machine. please help me on this.

**Comment by jahnni** [comment]
hi there, i had the same issue and finally realized i didn't install php5-curl...

**Comment by jryd** [comment]
I am getting the same issue. php5-curl is installed on my machine so it isn't that.

My `geocoder.php` file looks like this:

```
<?php

/**
 * This file is part of the GeocoderLaravel library.
 *
 * (c) Antoine Corcy <contact@sbin.dk>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

return [
    // Providers get called in the chain order given here.
    // The first one to return a result will be used.
    'providers' => [
        'Geocoder\Provider\GoogleMapsProvider' => ['en-EN', 'Australia', $ssl = true, 'xxxgoogle_maps_api_key'],
        'Geocoder\Provider\FreeGeoIpProvider'  => null,
    ],
    'adapter'  => 'Geocoder\HttpAdapter\CurlHttpAdapter',
];
```

And then in my controller:

```
try {
            $geocode = Geocoder::geocode('Brisbane, Australia');
            // The GoogleMapsProvider will return a result
            var_dump($geocode);
        } catch (\Exception $e) {
            // No exception will be thrown here
            echo $e->getMessage();
        }
```

This returns `No provider could provide the address "Brisbane, Australia"` for me every time.

Any ideas?

**Comment by jryd** [comment]
Using the solution @fabioi suggests works for me. However we shouldn't have to do all that inside the controller right?

**Comment by mikebronner** [comment]
@jryd You are absolutely correct, most of that should be extracted out to the Service Provider. We are working on getting an new release out real soon that will bring it up to par with the latest Geocoder version, and work with a single line of code, something like:
```php
app('geocode')->geocode('your address here');
```

(Or similar.) I'm working out the final details and writing some unit tests, and should have a new version ready soon there-after.

**Comment by jryd** [comment]
Awesome, thanks @mikebronner

**Comment by sahamilton** [comment]
Is there any update on this issue? I have tried fabio's suggestion but to date not results.  I have tracked and proved that the query is generating correctly (dd($query) at function geocode in GoogleMaps) so it is clearly an issue with the Curl call.  Curl is installed in my environment and the package works fine in the Laravel 4.2 version (Im finally upgrading :-( )
