### ISSUE TITLE
Don't cache result if result = null when api request fails

### ISSUE THREAD

**Issue by scottgrayson** [geocoder-php/GeocoderLaravel#143]
### General Information
GeocoderLaravel Version: 4.0.0
Laravel Version: 5.6.39
PHP Version: 7.2.8
Operating System and Version: mac os 10.13.6

### Issue Description
Empty results should not always be cached as the result.

Sometimes it makes sense. Like if the api requests were all successful and the address did not find anything

Other times, I would like to retry the api call instead of pulling `null` from the cache. Like when api key was invalid or daily limit was hit.

### Steps to Replicate
1. setup geocode cache
1. geocode address with invalid api key
2. see no result (expected)
3. change api key to valid key
4. geocode the same address
5. no result (i would like it to retry instead of pull from cache)

### Stack Trace
no error. but I would like there to be one when api request fails. (e.g. limit reached, invalid api key)

**Comment by scottgrayson** [comment]
just realized that i can get errors with using('google_maps') instead of chain. that makes sense.

This fixes the problem for me

Although, it still seems like it could be useful to not cache null for the result when all chain providers failed (api request error)

**Comment by adddz** [comment]
Hi @scottgrayson, how were you able to not cache empty results? I have a bunch of cached empty results that I don't know how to purge, too.
