### ISSUE TITLE
Geo Coder syntax error issue

### ISSUE THREAD

**Issue by wahabahmadbutt** [geocoder-php/GeocoderLaravel#147]
Laravel Version: 5.4
PHP Version: 7.0.31
Operating System and Version: Windows 10

Hi i have installed the package and i am facing the issue 
exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ':', expecting ';' or '{'' in /srv/www/madison_api/releases/20190218080731/vendor/spatie/geocoder/src/Geocoder.php:63
Please help me

**Comment by mikebronner** [comment]
@wahabahmadbutt The problem lies in a different package. This is not the Spatie geocoded package.
