### ISSUE TITLE
Laravel error Trying to get property 'result' of non-object

### ISSUE THREAD

**Issue by startcrowds** [geocoder-php/GeocoderLaravel#151]
public function get_address()
    {
        $fields = array(
                "jsonrpc" => '2.0',
                "method" => 'createAddressForToken',
                "params" => array('password'),
                "id" => '1',
        );
        $fields = json_encode($fields);
        $headers = array(
            'Content-Type: application/json'
        );

        $ch = curl_init();
        curl_setopt($ch, CURLOPT_URL, APIURL);
        curl_setopt($ch, CURLOPT_POST, true);
        curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($ch, CURLOPT_POSTFIELDS, $fields);
        $result = curl_exec($ch);
        curl_close($ch);
        $response=json_decode($result);        
        if(isset($response->error->code))
        {
        	return $address=0;	
        }
        else
        {        	
        	return $address=$response->result;
        }
    }
}

**Comment by startcrowds** [comment]
Error is in the line return $address=$response->result;

**Comment by mikebronner** [comment]
@startcrowds Could you elaborate on what you are referencing? Where is this code? What is the issue?

**Comment by startcrowds** [comment]
This code queries a smart contract associated with an ethereum address, but it gives me a value of null and does not recognize it as an object

**Comment by mikebronner** [comment]
I'm not sure what this has to do with this package?

**Comment by startcrowds** [comment]
Ok Bro thanks!
