### ISSUE TITLE
Installation issues with Laravel 6.1

### ISSUE THREAD

**Issue by JaZo** [geocoder-php/GeocoderLaravel#160]
### General Information
GeocoderLaravel Version: 4.2.0
Laravel Version: 6.0, trying to install 6.1
PHP Version: 7.2
Operating System and Version: Ubuntu 18.04.3 LTS

### Issue Description
I can't update to Laravel 6.1 because #156 only added support for 6.0. Laravel is following semver now, so requiring '^6.0' should be fine.

### Steps to Replicate
1. Start new Laravel 6.0 project;
2. Install toin0u/geocoder-laravel;
3. Run `composer why-not "laravel/framework:^6.1"`;
4. See "toin0u/geocoder-laravel  4.2.0  requires  illuminate/support (5.0 - 6.0)".

**Comment by mikebronner** [comment]
Thanks for reporting this :) I'll try to get this updated today or tomorrow (I've been out of the office for two weeks, so will be catching up and updating all my packages over the next few days).
