### ISSUE TITLE
Algolia Provider

### ISSUE THREAD

**Issue by tanthammar** [geocoder-php/GeocoderLaravel#163]
### General Information
GeocoderLaravel Version: ^4.2
Laravel Version: 6
PHP Version: 7.3.8
Operating System and Version: OSX 10.14.6

### Issue Description
I do understand that this might not be the proper place to ask, but I was hoping that someone might have a solution. :)

Unable to get this to work with the Algolia geocoder provider
No errors, but always an empty collection returned.

(I have it working with the Nominatim and GoogleMaps)

### Steps to Replicate
```
composer require geocoder-php/algolia-places-provider^0.1.1
```
in `config/geocoder.php`
```js
'providers' => [
        Chain::class => [
            AlgoliaPlaces::class => [
                'my-api-key',
                'my-app-id'
            ],
            Nominatim::class => [
                'https://nominatim.openstreetmap.org',
                'en'
            ],
            GoogleMaps::class => [
                env('GOOGLE_MAPS_LOCALE', 'en-US'),
                env('GOOGLE_MAPS_API_KEY'),
            ],
            GeoPlugin::class  => [],
        ],
    ],
```
### Stack Trace
[if an error is occuring, provide the complete stack trace here]

**Comment by mikebronner** [comment]
I posted this in the correct repo for you (see above link).

**Comment by mikebronner** [comment]
@tanthammar Please continue the discussion in the other thread. They are asking for more details. Good luck.
