### ISSUE TITLE
Undefined property: Geocoder\Provider\GoogleMaps\Model\GoogleAddress::$coordinates

### ISSUE THREAD

**Issue by sheinfeld** [geocoder-php/GeocoderLaravel#168]
### General Information
GeocoderLaravel Version: Latest
Laravel Version: 6.
PHP Version: 7.3+
Operating System and Version: Windows 10

### Issue Description
I am trying to call the property "coordinates", but I always get the error "Undefined property: Geocoder\Provider\GoogleMaps\Model\GoogleAddress::$coordinates".

When I dd the object without "->coordinates" it shows everything, including the coordinates!

### Steps to Replicate
` $geoData = Geocoder::geocode($address)->get()->first();
           dd($geoData->coordinates);`

### Stack Trace
"""
#0 C:\wamp64\www\ocasiao_cms\app\Http\Controllers\Controller.php(140): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'Undefined prope...', 'C ▶
#1 C:\wamp64\www\ocasiao_cms\app\Http\Controllers\ClassifiedController.php(117): App\Http\Controllers\Controller->getGeoPositionFromAddress('Lisboa, Portuga...' ▶
#2 [internal function]: App\Http\Controllers\ClassifiedController->editPost(Object(App\Http\Requests\ClassifiedRequest))
#3 C:\wamp64\www\ocasiao_cms\vendor\laravel\framework\src\Illuminate\Routing\Controller.php(54): call_user_func_array(Array, Array)
#4 C:\wamp64\www\ocasiao_cms\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(45): Illuminate\Routing\Controller->callAction('editPost', ▶
#5 C:\wamp64\www\ocasiao_cms\vendor\laravel\framework\src\Illuminate\Routing\Route.php(219): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate ▶
#6 C:\wamp64\www\ocasiao_cms\vendor\laravel\framework\src\Illuminate\Routing\Route.php(176): Illuminate\Routing\Route->runController()
#7 C:\wamp64\www\ocasiao_cms\vendor\laravel\framework\src\Illuminate\Routing\Router.php(681): Illuminate\Routing\Route->run()
#8 C:\wamp64\www\ocasiao_cms\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(130): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object( ▶
#9 C:\wamp64\www\ocasiao_cms\vendor\cybercog\laravel-ban\src\Http\Middleware\LogsOutBannedUser.php(61): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closu ▶
#10 C:\wamp64\www\ocasiao_cms\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Cog\Laravel\Ban\Http\Middleware\LogsOutBannedUser->handle(Obje ▶
#11 C:\wamp64\www\ocasiao_cms\vendor\laravel\framework\src\Illuminate\Auth\Middleware\EnsureEmailIsVerified.php(29): Illuminate\Pipeline\Pipeline->Illuminate\Pi ▶
#12 C:\wamp64\www\ocasiao_cms\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Illuminate\Auth\Middleware\EnsureEmailIsVerified->handle(Objec ▶
#13 C:\wamp64\www\ocasiao_cms\vendor\laravel\framework\src\Illuminate\Routing\Middleware\SubstituteBindings.php(41): Illuminate\Pipeline\Pipeline->Illuminate\Pi ▶
#14 C:\wamp64\www\ocasiao_cms\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Illuminate\Routing\Middleware\SubstituteBindings->handle(Objec ▶
#15 C:\wamp64\www\ocasiao_cms\vendor\laravel\framework\src\Illuminate\Auth\Middleware\Authenticate.php(43): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{c ▶
#16 C:\wamp64\www\ocasiao_cms\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Illuminate\Auth\Middleware\Authenticate->handle(Object(Illumin ▶
#17 C:\wamp64\www\ocasiao_cms\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\VerifyCsrfToken.php(76): Illuminate\Pipeline\Pipeline->Illumina ▶
#18 C:\wamp64\www\ocasiao_cms\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle( ▶
#19 C:\wamp64\www\ocasiao_cms\vendor\laravel\framework\src\Illuminate\View\Middleware\ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\P ▶
#20 C:\wamp64\www\ocasiao_cms\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Obje ▶
#21 C:\wamp64\www\ocasiao_cms\vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php(56): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline ▶
#22 C:\wamp64\www\ocasiao_cms\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Illuminate\Session\Middleware\StartSession->handle(Object(Illu ▶
#23 C:\wamp64\www\ocasiao_cms\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illumi ▶
#24 C:\wamp64\www\ocasiao_cms\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handl ▶
#25 C:\wamp64\www\ocasiao_cms\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\EncryptCookies.php(66): Illuminate\Pipeline\Pipeline->Illuminate\Pipelin ▶
#26 C:\wamp64\www\ocasiao_cms\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Ill ▶
#27 C:\wamp64\www\ocasiao_cms\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Ob ▶
#28 C:\wamp64\www\ocasiao_cms\vendor\laravel\framework\src\Illuminate\Routing\Router.php(683): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#29 C:\wamp64\www\ocasiao_cms\vendor\laravel\framework\src\Illuminate\Routing\Router.php(658): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\ ▶
#30 C:\wamp64\www\ocasiao_cms\vendor\laravel\framework\src\Illuminate\Routing\Router.php(624): Illuminate\Routing\Router->runRoute(Object(Illuminate\Http\Reques ▶
#31 C:\wamp64\www\ocasiao_cms\vendor\laravel\framework\src\Illuminate\Routing\Router.php(613): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http ▶
#32 C:\wamp64\www\ocasiao_cms\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(170): Illuminate\Routing\Router->dispatch(Object(Illuminate\Htt ▶
#33 C:\wamp64\www\ocasiao_cms\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(130): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\ ▶
#34 C:\wamp64\www\ocasiao_cms\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illumi ▶
#35 C:\wamp64\www\ocasiao_cms\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Illuminate\Foundation\Http\Middleware\TransformsRequest->handl ▶
#36 C:\wamp64\www\ocasiao_cms\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illumi ▶
#37 C:\wamp64\www\ocasiao_cms\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Illuminate\Foundation\Http\Middleware\TransformsRequest->handl ▶
#38 C:\wamp64\www\ocasiao_cms\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\ValidatePostSize.php(27): Illuminate\Pipeline\Pipeline->Illumin ▶
#39 C:\wamp64\www\ocasiao_cms\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle ▶
#40 C:\wamp64\www\ocasiao_cms\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode.php(63): Illuminate\Pipeline\Pipeline-> ▶
#41 C:\wamp64\www\ocasiao_cms\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode- ▶
#42 C:\wamp64\www\ocasiao_cms\vendor\fideloper\proxy\src\TrustProxies.php(57): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Htt ▶
#43 C:\wamp64\www\ocasiao_cms\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Re ▶
#44 C:\wamp64\www\ocasiao_cms\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Ob ▶
#45 C:\wamp64\www\ocasiao_cms\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(145): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#46 C:\wamp64\www\ocasiao_cms\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(110): Illuminate\Foundation\Http\Kernel->sendRequestThroughRout ▶
#47 C:\wamp64\www\ocasiao_cms\public\index.php(55): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#48 C:\wamp64\www\ocasiao_cms\server.php(21): require_once('C:\\wamp64\\www\\o...')
#49 {main}
"""

**Comment by mikebronner** [comment]
I believe you need to call `->getCoordinates()`, you can't access the properties directly.
