### ISSUE TITLE
How can I get multiple results from GoogleMaps when geocoding?

### ISSUE THREAD

**Issue by cinilak** [geocoder-php/GeocoderLaravel#17]
Apologies if this is a silly question, but I wasn't able to get multiple results which I would get when using Google geocode API nativelly (on it's own).

**Comment by toin0u** [comment]
Hi @cinilak :) There is no silly question !
The Geocoder ~2.x uses a ResultFactory. The DefaultResultFactory takes into account only the first result. If you need mutilple results you need to use the setter:
```php
// ...
Geocoder::setResultFactory(new \Geocoder\Result\MultipleResultFactory);
// ...
```

Hope this will help you :) Feel free to open/comment this ticket if you need more assistance !

**Comment by cinilak** [comment]
Lovely, thank you so much!

**Comment by toin0u** [comment]
You're welcome :)
