### ISSUE TITLE
How to override Locale and API key on controller?

### ISSUE THREAD

**Issue by elfeffe** [geocoder-php/GeocoderLaravel#177]
This is more a question, is there any way to override the locale and the API?

**Comment by mikebronner** [comment]
Yes, you can do it either in config, or during runtime, as explained here: https://github.com/geocoder-php/Geocoder/pull/408#discussion_r24653135

Hope this helps :)

**Comment by elfeffe** [comment]
Thank you @mikebronner 
But that’s for a chain, it is not the same, right?
How do you set locale here?
app('geocoder')->geocode('Los Angeles, CA')->get();

**Comment by mikebronner** [comment]
@elfeffe You cannot set the locale on the query, you have to set it on the provider. The chain is like any other provider. Instead of chain in that example, you would need to spin up a GoogleMaps or Bing or whichever provider you want to use with your desired locale. Hope that helps?

**Comment by elfeffe** [comment]
Ok, thanks for your help
