### ISSUE TITLE
Laravel 5 Support

### ISSUE THREAD

**Issue by verkaufer** [geocoder-php/GeocoderLaravel#18]
Are there any plans to test this with Laravel 5?

**Comment by toin0u** [comment]
I didn't planned yet but it should be done :)

**Comment by funkflute** [comment]
+1

**Comment by zhuston** [comment]
:+1:

**Comment by aoverall** [comment]
+1

**Comment by toin0u** [comment]
@verkaufer @funkflute @zhuston @aoverall I've just committed a version which should work with Laravel 5 in the master branch. Can you please try this version `"toin0u/geocoder-laravel": "0.4.*@dev"` and come with some feedbacks please ? :) If it's working as expected I'll update the doc and tag a new version.

**Comment by verkaufer** [comment]
Composer still thinks geocoder-laravel wants illuminate/support=~4.0


  Problem 1
    - Conclusion: remove laravel/framework v5.0.7
    - toin0u/geocoder-laravel 0.4.0 requires illuminate/support ~4.0 -> satisfiable by illuminate/support[v4.0.0, ... {just repeated incrementing versions listed here} ... v4.2.9].
    - toin0u/geocoder-laravel 0.4.1 requires illuminate/support ~4.0 -> satisfiable by illuminate/support[v4.0.0, v4.0.1, v4.0.10, v4.0.2, v4.0.3, v4.0.4, v4.0.5, v4.0.6, v4.0.7, v4.0.8, v4.0.9, v4.1.0, v4.1.1, v4.1.10, v4.1.11, v4.1.12, v4.1.13, v4.1.14, v4.1.15, v4.1.16, v4.1.17, v4.1.18, v4.1.19, v4.1.2, v4.1.20, v4.1.21, v4.1.22, v4.1.23, v4.1.24, v4.1.25, v4.1.26, v4.1.27, v4.1.28, v4.1.29, v4.1.3, v4.1.30, v4.1.4, v4.1.5, v4.1.6, v4.1.7, v4.1.8, v4.1.9, v4.2.1, v4.2.12, v4.2.16, v4.2.17, v4.2.2, v4.2.3, v4.2.4, v4.2.5, v4.2.6, v4.2.7, v4.2.8, v4.2.9].
    - toin0u/geocoder-laravel 0.4.x-dev requires illuminate/support ~4.0 -> satisfiable by illuminate/support[v4.0.0, v4.0.1, v4.0.10, v4.0.2, v4.0.3, v4.0.4, v4.0.5, v4.0.6, v4.0.7, v4.0.8, v4.0.9, v4.1.0, v4.1.1, v4.1.10, v4.1.11, v4.1.12, v4.1.13, v4.1.14, v4.1.15, v4.1.16, v4.1.17, v4.1.18, v4.1.19, v4.1.2, v4.1.20, v4.1.21, v4.1.22, v4.1.23, v4.1.24, v4.1.25, v4.1.26, v4.1.27, v4.1.28, v4.1.29, v4.1.3, v4.1.30, v4.1.4, v4.1.5, v4.1.6, v4.1.7, v4.1.8, v4.1.9, v4.2.1, v4.2.12, v4.2.16, v4.2.17, v4.2.2, v4.2.3, v4.2.4, v4.2.5, v4.2.6, v4.2.7, v4.2.8, v4.2.9].
    - don't install illuminate/support v4.0.0|don't install laravel/framework v5.0.7
    - don't install illuminate/support v4.0.1|don't install laravel/framework v5.0.7
    - don't install illuminate/support v4.0.10|don't install laravel/framework v5.0.7
    - don't install illuminate/support v4.0.2|don't install laravel/framework v5.0.7
    - don't install illuminate/support v4.0.3|don't install laravel/framework v5.0.7
    - don't install illuminate/support v4.0.4|don't install laravel/framework v5.0.7
    - don't install illuminate/support v4.0.5|don't install laravel/framework v5.0.7
    - don't install illuminate/support v4.0.6|don't install laravel/framework v5.0.7
    - don't install illuminate/support v4.0.7|don't install laravel/framework v5.0.7
    - don't install illuminate/support v4.0.8|don't install laravel/framework v5.0.7
    - don't install illuminate/support v4.0.9|don't install laravel/framework v5.0.7
    - don't install illuminate/support v4.1.0|don't install laravel/framework v5.0.7
    - don't install illuminate/support v4.1.1|don't install laravel/framework v5.0.7
    - don't install illuminate/support v4.1.10|don't install laravel/framework v5.0.7
    - don't install illuminate/support v4.1.11|don't install laravel/framework v5.0.7
    - don't install illuminate/support v4.1.12|don't install laravel/framework v5.0.7
    - don't install illuminate/support v4.1.13|don't install laravel/framework v5.0.7
    - don't install illuminate/support v4.1.14|don't install laravel/framework v5.0.7
    - don't install illuminate/support v4.1.15|don't install laravel/framework v5.0.7
    - don't install illuminate/support v4.1.16|don't install laravel/framework v5.0.7
    - don't install illuminate/support v4.1.17|don't install laravel/framework v5.0.7
    - don't install illuminate/support v4.1.18|don't install laravel/framework v5.0.7
    - don't install illuminate/support v4.1.19|don't install laravel/framework v5.0.7
    - don't install illuminate/support v4.1.2|don't install laravel/framework v5.0.7
    - don't install illuminate/support v4.1.20|don't install laravel/framework v5.0.7
    - don't install illuminate/support v4.1.21|don't install laravel/framework v5.0.7
    - don't install illuminate/support v4.1.22|don't install laravel/framework v5.0.7
    - don't install illuminate/support v4.1.23|don't install laravel/framework v5.0.7
    - don't install illuminate/support v4.1.24|don't install laravel/framework v5.0.7
    - don't install illuminate/support v4.1.25|don't install laravel/framework v5.0.7
    - don't install illuminate/support v4.1.26|don't install laravel/framework v5.0.7
    - don't install illuminate/support v4.1.27|don't install laravel/framework v5.0.7
    - don't install illuminate/support v4.1.28|don't install laravel/framework v5.0.7
    - don't install illuminate/support v4.1.29|don't install laravel/framework v5.0.7
    - don't install illuminate/support v4.1.3|don't install laravel/framework v5.0.7
    - don't install illuminate/support v4.1.30|don't install laravel/framework v5.0.7
    - don't install illuminate/support v4.1.4|don't install laravel/framework v5.0.7
    - don't install illuminate/support v4.1.5|don't install laravel/framework v5.0.7
    - don't install illuminate/support v4.1.6|don't install laravel/framework v5.0.7
    - don't install illuminate/support v4.1.7|don't install laravel/framework v5.0.7
    - don't install illuminate/support v4.1.8|don't install laravel/framework v5.0.7
    - don't install illuminate/support v4.1.9|don't install laravel/framework v5.0.7
    - don't install illuminate/support v4.2.1|don't install laravel/framework v5.0.7
    - don't install illuminate/support v4.2.12|don't install laravel/framework v5.0.7
    - don't install illuminate/support v4.2.16|don't install laravel/framework v5.0.7
    - don't install illuminate/support v4.2.17|don't install laravel/framework v5.0.7
    - don't install illuminate/support v4.2.2|don't install laravel/framework v5.0.7
    - don't install illuminate/support v4.2.3|don't install laravel/framework v5.0.7
    - don't install illuminate/support v4.2.4|don't install laravel/framework v5.0.7
    - don't install illuminate/support v4.2.5|don't install laravel/framework v5.0.7
    - don't install illuminate/support v4.2.6|don't install laravel/framework v5.0.7
    - don't install illuminate/support v4.2.7|don't install laravel/framework v5.0.7
    - don't install illuminate/support v4.2.8|don't install laravel/framework v5.0.7
    - don't install illuminate/support v4.2.9|don't install laravel/framework v5.0.7
    - Installation request for laravel/framework == 5.0.7.0 -> satisfiable by laravel/framework[v5.0.7].
    - Installation request for toin0u/geocoder-laravel 0.4.*@dev -> satisfiable by toin0u/geocoder-laravel[0.4.0, 0.4.1, 0.4.x-dev].

**Comment by toin0u** [comment]
That's pretty weird... https://github.com/geocoder-php/GeocoderLaravel/blob/master/composer.json#L17

**Comment by verkaufer** [comment]
I removed the `minimum-stability` from `composer.json` and clear the composer cache, but that didn't make a difference.

**Comment by toin0u** [comment]
Ok thanks for your feedback. There is obviously more work to do for that :)

**Comment by verkaufer** [comment]
If it helps any, your geotools-laravel package installs without any issues for L5 :)

**Comment by toin0u** [comment]
Thank you @verkaufer :)

**Comment by verkaufer** [comment]
Just an update: 

Using toin0u/geocoder-laravel: "dev-master" works when used in composer.json. The package works perfectly, so I think the only issue is tagging it for release.

**Comment by toin0u** [comment]
Cool! So I just need to update the doc and tag the master branch then :)

**Comment by toin0u** [comment]
I've just tagged a new version :) Thanks everyone for your help!
> https://github.com/geocoder-php/GeocoderLaravel/releases/tag/0.5.0
