### ISSUE TITLE
I need to purge the empty cached results, how?

### ISSUE THREAD

**Issue by adddz** [geocoder-php/GeocoderLaravel#183]
As many others already mentioned, the library caches empty results (empty collections). All good up to here, but how can I purge those results?

**Comment by adddz** [comment]
I guess nobody is maintaining this repo anymore? :(

**Comment by mikebronner** [comment]
@adddz Sorry for the late reply. Right now to purge those you would do something like `php artisan cache:clear`.

**Comment by mikebronner** [comment]
Just released 4.4.5 with the PR that clears items from cache.

**Comment by adddz** [comment]
> Just released 4.4.5 with the PR that clears items from cache.

Hi Mike, thank you so much.

Will this work even for when an address gets assigned latitude and longitude `0.000000`?

**Comment by mikebronner** [comment]
@adddz unfortunately not. It will only remove the empty results. I'll be happy to consider a PR, if you have time to submit one.

**Comment by adddz** [comment]
> @adddz unfortunately not. It will only remove the empty results. I'll be happy to consider a PR, if you have time to submit one.

Sure. Just to understand, let's say the geocoder returns `0.000000` as lat/lng for an address, will it still save it in the cache then? I was thinking of adding a method to the geocoder that removes only a specific item from the cache.

**Comment by mikebronner** [comment]
I believe that is correct: https://github.com/geocoder-php/GeocoderLaravel/pull/186/files#diff-acda5d354b2c91ce241087f5ae72c8c836de52a45ab812a69f2b5294fe9266c0R322

Perhaps you can add the appropriate logic there, if it makes sense to do so.
