### ISSUE TITLE
HERE Provider: Can't pass apiKey in configuration

### ISSUE THREAD

**Issue by bastian-schur** [geocoder-php/GeocoderLaravel#199]
### General Information
GeocoderLaravel Version: 4.7.0
Laravel Version: 8.83.27
PHP Version: 8.0
Operating System and Version: Ubuntu 22.04

### Issue Description
Since HERE disabled his old developer portal and started with HERE platform, only apiKey is allowed. The HERE Provider constructor currently accepts only app_id and app_key. The package docs show a workaround like this:
`$provider = \Geocoder\Provider\Here\Here::createUsingApiKey($httpClient, 'your-api-key');`

But I'm searching for a way to pass this into the geocoder.php configuration.

Is this possible?

**Comment by mikebronner** [comment]
Hi @bastian-schur, this is an issue with the GeoCoder core package and related HERE provider. Please see issue already raised there, for example: https://github.com/geocoder-php/Geocoder/issues/1054
