### ISSUE TITLE
Nothing to publish

### ISSUE THREAD

**Issue by 1915** [geocoder-php/GeocoderLaravel#25]
Going with the instructions, but when I get to this part:
php artisan vendor:publish --provider="toin0u/geocoder-laravel"

The cli just returns "Nothing to publish". No config file is written and nothing is written to config/services

Tried on both 0.5.0 and 0.5.x-dev.

**Comment by ijett** [comment]
I confirm
the same problem, laravel 5.0.*, GeoLaravel 0.5.0

**Comment by zawilliams** [comment]
Same issue here. Running laravel 5.0.* and GeoLaravel 0.5.0

**Comment by zawilliams** [comment]
I just ran only `php artisan vendor:publish` instead of with the provider tag and it published. Strange.

**Comment by ijett** [comment]
zawilliams, really its work, good!

**Comment by SimonErich** [comment]
If you only want to publish config and so on for this package only, you can also use:
```php artisan vendor:publish --provider="Toin0u\Geocoder\GeocoderServiceProvider"```

**Comment by zawilliams** [comment]
Thanks @SimonErich - that works!
