### ISSUE TITLE
Laravel 5.1 Support

### ISSUE THREAD

**Issue by CWSpear** [geocoder-php/GeocoderLaravel#27]
Currently, the `"illuminate/support"  : "5.0.*",` require statement makes this unable to install on Laravel 5.1, which needs `laravel/support` >= 5.1

**Comment by azcoppen** [comment]
+1

**Comment by victor-ponamariov** [comment]
+1

**Comment by scalerboy** [comment]
+1

**Comment by chungth** [comment]
+1

**Comment by ferrysutanto19** [comment]
+1

**Comment by Ycfx** [comment]
+1

**Comment by willdurand** [comment]
@Ycfx I think it's fixed.

**Comment by Ycfx** [comment]
thank you i realized that,
sorry.
