### ISSUE TITLE
It does not work with Laravel 5.1

### ISSUE THREAD

**Issue by bart** [geocoder-php/GeocoderLaravel#31]
Would you please update the dependencies to Laravel ~5.1? Thanks dude.

Getting:
```
toin0u/geocoder-laravel 0.5.0 requires illuminate/support 5.0.*
```

**Comment by bart** [comment]
Okay it seems like you have to give packagist a refresh, because in https://packagist.org/packages/toin0u/geocoder-laravel#dev-master Laravel 5.0.* is set as requirement with the last update from 2015-04-16 07:50 UTC which is wrong.

**Comment by gilbertsmith** [comment]
Getting the same thing. Need the dependencies updated to 5.0 +

**Comment by martinbean** [comment]
+1.

Package needs updating on Packagist, as it’s still reporting illuminate/support 5.0.* is required, therefore I can’t install it in my 5.1.* Laravel application.

**Comment by richcoremedia** [comment]
waiting for the update at ~L5.1

**Comment by jakeryansmith** [comment]
+1

**Comment by martinbean** [comment]
@toin0u @willdurand Can one of you guys take a look at this when you get a couple of minutes spare, please?

**Comment by jbdivups** [comment]
+1

**Comment by martinbean** [comment]
What’s the hold up with this?

**Comment by bart** [comment]
None of the main contributors does trigger a refresh on packagist. This is very annoying.

**Comment by mikefrancis** [comment]
+1

**Comment by pbean** [comment]
Hey folks,

wanted to say I put together a workaround until its updated on packagist. I unfortunately don't have the time to wait I have a project due very soon and this is one of the last pieces i wanted to utilize to save me a massive headache. in your composer json, right above require add:
```
"repositories": [
	  {
		"type": "vcs",
		"url": "https://github.com/geocoder-php/GeocoderLaravel"
	  }
	],
```
and in require add
```
"toin0u/geocoder-laravel": "dev-master"
```

everything now installs properly. I'm new to the whole composer and back end development, haven't done any web development in 10 years and had to pick up the pieces of a failed project in a short timeline so i'm working fast and I couldn't find a specific answer that safely answered to my noob level. hope this helps folks

**Comment by willdurand** [comment]
I don't have admin rights on Packagist. @toin0u is on vacations right now, so let's wait a bit.

**Comment by pbean** [comment]
Hey folks

I'm on a tight timeline for a project and I needed this package so I put together a work around. I'll include it here hoping to help others if they absolutely need it since the git master branch already has the package dependencies updated.

add this above your require in your composer.json
```
"repositories": [
	  {
		"type": "vcs",
		"url": "https://github.com/geocoder-php/GeocoderLaravel"
	  }
	],
```
This will pull from github instead once you have that placed you can then add the following as the package in require
```
"toin0u/geocoder-laravel": "dev-master",
```
That will pull the master branch from git and everything works okey dokey to bypass the composer package dependency. I ended up going down another route with everything for now and will probably circle back to using this later on this week but the few things i tested seemed to work.

**Comment by bart** [comment]
Thanks for your reply @pbean. This is a good temporary workaround for sure, but I wanna wait for @toin0u being back from holidays.

@willdurand Do you know when he is back?

**Comment by willdurand** [comment]
Ok folks, I've released [0.6.0](https://github.com/geocoder-php/GeocoderLaravel/releases/tag/0.6.0). Let me know if it works for you.

**Comment by martinbean** [comment]
@willdurand The issue isn’t the version of GeocoderLaravel. The issue is it’s not been updated on Packagist: https://packagist.org/packages/toin0u/geocoder-laravel

If you look, it says it requires version 5.0.* of illuminate/support, which means it’s locked to Laravel version 5.0.* only.

**Comment by willdurand** [comment]
Ok. It should be better now.

**Comment by bart** [comment]
Looks good on packagist now, thanks a lot!

**Comment by martinbean** [comment]
W00t!
