### ISSUE TITLE
Get list of cities come under geometric rectangle bounds

### ISSUE THREAD

**Issue by eswarreddy43** [geocoder-php/GeocoderLaravel#32]
In my app user will select specific area on google map with rectangle, circle or polygon. So from that selected area, i need to list down the cities.

For example user selected rectangle shape on google map with following bounds:

```
{South West : (37.37015718405753, -105.29296875), North East : (41.64007838467894, -95.80078125) }
```

So do we have any function for getting cities list using Geocode?

**Comment by mikebronner** [comment]
At this time there is no bounds lookup on the GoogleMaps provider. This would be a good thing to submit as an issue on the geocoder-php repo (or even a PR).

**Comment by eswarreddy43** [comment]
Yes, Thanks @mikebronner for your valuable input.

**Comment by mikebronner** [comment]
Closing for now, please re-open if this does end up being an issue.
