### ISSUE TITLE
Issue in getting latitude and longitude using Bing Maps

### ISSUE THREAD

**Issue by mitzz007** [geocoder-php/GeocoderLaravel#33]
After following all the steps written in github for implementing geo-coding, I got the output for google maps. Repeating the same steps for the bing maps I got the output (latitude and longitude) using correct API key.
Issue is: 
1: The value got from both the maps are not exactly same after decimal.
2: Bing map is not reliable (When I tried using bing map again after some period of time I didn't get the output).

This is what I got when I fired get command second time ,

object(Geocoder\Result\Geocoded)[846]
  protected 'latitude' => int 0
  protected 'longitude' => int 0
  protected 'bounds' => null
  protected 'streetNumber' => null
  protected 'streetName' => null
  protected 'cityDistrict' => null
  protected 'city' => null
  protected 'zipcode' => null
  protected 'county' => null
  protected 'countyCode' => null
  protected 'region' => null
  protected 'regionCode' => null
  protected 'country' => null
  protected 'countryCode' => null
  protected 'timezone' => null

Please reply soon if anyone knows about this issue.

**Comment by mikebronner** [comment]
Has this been resolved, or is it still an issue? I don' t have a Bing Maps API key, but if its still an issue I will make one to try to reproduce.

**Comment by mikebronner** [comment]
Have not received a reply over the week, closing for now. If this is still an issue, please do re-open it, and we will look into it. :) Thanks!
