### ISSUE TITLE
Simple IP lookup generates error

### ISSUE THREAD

**Issue by simplenotezy** [geocoder-php/GeocoderLaravel#34]
I get the following error:

     Missing argument 2 for Alexpechkarev\GoogleGeocoder\GoogleGeocoder::geocode(), called in /home/vagrant/Projects/athliit/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php on line 210 and defined

When I try to do:

    Geocoder::geocode('my-ip-address');

With my config looking like so:

	<?php
	
	return [
		// Providers get called in the chain order given here.
		// The first one to return a result will be used.
		'providers' => [
			'Geocoder\Provider\FreeGeoIpProvider'  => null,
		],
		'adapter'  => 'Geocoder\HttpAdapter\CurlHttpAdapter',
	];

**Comment by zanematthew** [comment]
I don't see this as an issue reference an old issue #13 with that address it works as expected.

**Comment by zanematthew** [comment]
Recently updated my GitHub notifications settings, must say I do enjoy messages showing constant issue pruning :)

**Comment by mikebronner** [comment]
I'm trying :) hehe
