### ISSUE TITLE
Using Geocoder::geocode within a loop gets Server Time Out.

### ISSUE THREAD

**Issue by emarino0411** [geocoder-php/GeocoderLaravel#43]
Hi I have this code:

foreach ($results as $result) {
        $barangay = DB::table('rbrgy')->where('bgycode', $result->barangay)->first();
        $loc = getBrgyName($barangay->bgycode) . ', '
                . getCityName($barangay->citycode) . ', '
                . getProvName($barangay->provcode) . ', '
                . getRegion($barangay->regcode) . ', '
                . 'Philippines';
        $geocode = Geocoder::geocode($loc);
}

When the $results array is <= 10, it works fine but when $results is > 10, the I get a server timeout. Is there a way on how I can get multiple geocodes with one function call?

Please help. Tried searching the issues but there seems to be no issues related to this. Thanks in advance!

~May

**Comment by mikebronner** [comment]
Hi @emarino0411, can you provide more details:
- which adapter are you using?
- which provider are you using?

I have found that adding a wait time of 250ms between each request for GoogleMaps aleviates this (they rate-limit their APIs) -- other providers may do that as well.

**Comment by mikebronner** [comment]
Closing for now, no response. Please re-open if this is still an issue.
