### ISSUE TITLE
Use different geocoders

### ISSUE THREAD

**Issue by hohl** [geocoder-php/GeocoderLaravel#47]
Sometimes I want to geocode IP addresses of my users and sometimes I want to geocode addresses. For the IP addresses I would like to use the `FreeGeoIpProvider`, for the addresses I would like to use the `GoogleMapsProvider`. Is there any way to switch between the configured providers in code?

I've seen there is a method called `using` in the `Geocode` facade. However, I couldn't get it working.

**Comment by xitude** [comment]
Why dont you use `as` in the the namespace
e.g. 
`use FreeGeoIpProvider as FreeIP`
`use GoogleMapsProvider as GoogleMaps`

Then update the façade you call.

**Comment by hohl** [comment]
How should the `use` statement help me with my problem, xitude? I want to use the `Facade` provided by this plugin with different providers. If I would use the providers directly I wouldn't need that plugin at all because then I could have used the [Geocoder](http://geocoder-php.org/Geocoder/) package directly. (Which may not even a bad idea, since this plugin seems a bit outdated too, since it still does rely on Geocoder 2 [when there is Geocoder 3 out already for a while](https://github.com/geocoder-php/GeocoderLaravel/issues/22)).

**Comment by mikebronner** [comment]
@hohl, that's exactly what I did yesterday. Upgraded to the php version of geocoder, and it ended up being even easier to use than this one. While I appreciate the work done on this package, it being out of date is actually starting to cause problems (which were aleviated as soon as I implemented the current php package).

**Comment by xitude** [comment]
@hohl sorry I misread the question..

**Comment by mikebronner** [comment]
Working on new release ... will add example to documentation.

**Comment by mikebronner** [comment]
Having researched this some more, this will require a separate PR. However, I would like to implement it, as I think its increadibly useful. I will submit a PR to the parent repo, and if that is rejected, implement it locally for the laravel repo (however, that might cause some oddities as we would have diverging functionality, something we should avoid). If anyone wants to help out with this, please submit a PR to the main geocoder repo and reference this issue, if I don't get to it first, or if one hasn't already been created.

**Comment by mikebronner** [comment]
Figured out a better solution requiring no additional PR. Will be in next release. Please keep an eye on this and re-open if it happens again after release. Thanks :)
