### ISSUE TITLE
Update badges on README

### ISSUE THREAD

**Issue by willdurand** [geocoder-php/GeocoderLaravel#51]
I think we should change the badges now that we are back on Travis-CI, right?

**Comment by mikebronner** [comment]
Hi Will, unfortunately not yet (I left a comment as to why on the PR, but that probably didn't send out a notification).
TravisCI has a known CURL bug that prevents the tests from succeeding, so it will always show failing unit tests, no matter what, when that's not actually the case. I'd rather not show failing build badges if they aren't accurate. :)
Once Travis upgrades to Ubuntu16, I believe this will be fixed. I'll keep this open until Travis starts working again.

**Comment by willdurand** [comment]
A curl bug? With PHP stable versions?

I don't have notifications for GitHub, so I probably missed it sorry for the noise then...

**Comment by mikebronner** [comment]
It's actually an issue with the OpenSSL implementation. I will get the specifics and add them here.

**Comment by willdurand** [comment]
So, all version of PHP are affected? Looks pretty serious to me

**Comment by mikebronner** [comment]
The reason this is coming up now is because I am running end-to-end integration tests, which go out over the wire. (That wasn't happening before.) Here is a bit more illumination on the matter: http://stackoverflow.com/questions/38375211/curl-error-35-gnutls-handshake-failed

**Comment by mikebronner** [comment]
Added coveralls badge back to readme, now that Travis is resolving most of the geocoding service URIs in the tests. However, it is still failing an IP geocoding test (using FreeGeoIP) because of the above issue. This from the build log:

```
1) Geocoder\Laravel\Tests\Laravel5_3\Providers\GeocoderServiceTest::testItResolvesAGivenIPAddress
Http\Client\Exception\NetworkException: gnutls_handshake() failed: A TLS fatal alert has been received.
/home/travis/build/geocoder-php/GeocoderLaravel/vendor/php-http/curl-client/src/Client.php:134
/home/travis/build/geocoder-php/GeocoderLaravel/vendor/geocoder-php/common-http/Provider/AbstractHttpProvider.php:61
/home/travis/build/geocoder-php/GeocoderLaravel/vendor/geocoder-php/free-geoip-provider/FreeGeoIp.php:61
/home/travis/build/geocoder-php/GeocoderLaravel/vendor/willdurand/geocoder/ProviderAggregator.php:54
/home/travis/build/geocoder-php/GeocoderLaravel/vendor/willdurand/geocoder/ProviderAggregator.php:79
/home/travis/build/geocoder-php/GeocoderLaravel/src/ProviderAndDumperAggregator.php:118
/home/travis/build/geocoder-php/GeocoderLaravel/vendor/laravel/framework/src/Illuminate/Cache/Repository.php:288
/home/travis/build/geocoder-php/GeocoderLaravel/vendor/laravel/framework/src/Illuminate/Cache/CacheManager.php:302
/home/travis/build/geocoder-php/GeocoderLaravel/src/ProviderAndDumperAggregator.php:119
/home/travis/build/geocoder-php/GeocoderLaravel/tests/Laravel5_3/Providers/GeocoderServiceTest.php:71
```

I am trying to see if it can resolve any of the other geo-ip providers.

**Comment by mikebronner** [comment]
Solved by using GeoPlugin instead of FreeGeoIP -- looks like Travis doesn't have the cert chain for FreeGeoIP. Add Travis build badge back to readme.
