### ISSUE TITLE
[Feature Request] Apartment numbers (subpremise)

### ISSUE THREAD

**Issue by ellisio** [geocoder-php/GeocoderLaravel#52]
When parsing an address with an apartment number, you receive a "Subpremise" attribute. This attribute is typically mapped to an "Address Line 2".

For example: https://maps.googleapis.com/maps/api/geocode/json?address=2123%20W%20Mineral%20Ave%20Apt%2061,%20Littleton,%20CO%2080120

It would be nice to have this added as the `subpremise` on the `Address` object.

**Comment by mikebronner** [comment]
Will take a look this week, thanks for reporting this! :) (Fair warning, this might be an issue with the underlying geodocer-php library.)

**Comment by mikebronner** [comment]
Sorry its been taking so long to get a reply on this. Its on my radar, and will look at it as soon as possible. Happy Thanksgiving, everyone!

**Comment by mikebronner** [comment]
This is actually an issue with GeocoderPHP itself. (I pend this as an issue there: https://github.com/geocoder-php/Geocoder/issues/593.)

Looking at the code, the `Address` model does not have any address line 2 properties, so that would have to be added.

**Comment by mikebronner** [comment]
@ellisio Quick update: the functionality will be added in the next major release of geocoded-php, and will make its way into this package then. :)

**Comment by ellisio** [comment]
@mikebronner Awesome, thank you for the update! This'll be helpful with a feature we're currently R&Ding. 👍

**Comment by mikebronner** [comment]
Good to hear! Keep us updated on how it works. Best guess is that the update is about 3 weeks out, but you can download dev-master of this package and start using it.
