### ISSUE TITLE
What is the vendor::publish command?

### ISSUE THREAD

**Issue by scottgrayson** [geocoder-php/GeocoderLaravel#53]
```
php artisan vendor:publish --provider="Geocoder\Laravel\GeocoderServiceProvider" --tags="config"

[Symfony\Component\Console\Exception\RuntimeException]
  The "--tags" option does not exist.
```
```
php artisan vendor:publish --provider="Geocoder\Laravel\GeocoderServiceProvider" --tag="config"

Nothing to publish for tag [config].
```
```
php artisan vendor:publish --provider="Toin0u\Geocoder\GeocoderServiceProvider"

Nothing to publish for tag [].
```
tried a few different ones. I assume i just need to copy paste the config/geocoder.php to my app

**Comment by mikebronner** [comment]
Let me take a look this week as to what is going on. Thanks for reporting this. Planning to release v1 final this weekend. :)

**Comment by mikebronner** [comment]
Sorry its been taking so long to get a reply on this. Its on my radar, and will look at it as soon as possible. Happy Thanksgiving, everyone!

**Comment by ganchclub** [comment]
You need to change the namespace of the provider. Command should be: 
`php artisan vendor:publish --provider="Geocoder\Laravel\Providers\GeocoderService" --tag=config`
Result then should be:
`Copied File [/vendor/toin0u/geocoder-laravel/config/geocoder.php] To [/config/geocoder.php]
Publishing complete for tag [config]!`

**Comment by ganchclub** [comment]
@mikebronner 
it would be nice to update the documentation.

**Comment by mikebronner** [comment]
Getting this in place today. My apologies for the delay.

**Comment by andreasba** [comment]
Just wanted to let you know that for me the updated command still does not do anything:

`
$ php artisan vendor:publish --provider="Geocoder\Laravel\Providers\GeocoderService" --tag=config
Publishing complete.
`
=> no file has been copied (I had to do this by hand)

**Comment by mikebronner** [comment]
@andreasba I just ran the command (copy/pasted from your post) and it worked in my system. Please provide the following details:

Laravel version: (from composer.lock file)
GeocoderLaravel version: (from composer.lock file)
PHP version: (php -v from terminal)

**Comment by andreasba** [comment]
Hi @mikebronner thanks for the quick reply.

Laravel version is v5.4.23
Geocoder version is 1.0.5
PHP version is PHP 5.6.15 (cli) (built: Nov  9 2015 13:03:20) (this is my dev XAMPP machine)

**Comment by mikebronner** [comment]
Can you provide a complete stack trace from `/storage/logs/laravel.log` and any error output in the terminal? I can't reproduce this at this time. Can you try this in Homestead?

**Comment by andreasba** [comment]
Hi @mikebronner - after rebooting my PC today, it works - I dunno why, sorry for the false alarm!

**Comment by mikebronner** [comment]
@andreasba Good to hear :) thanks for the update.
