### ISSUE TITLE
No provider could geocode address

### ISSUE THREAD

**Issue by jryd** [geocoder-php/GeocoderLaravel#55]
I've followed the steps outlined to get this package installed in a new project I am working on in Laravel 5.3.

My `geocoder.php` file is set up like so:

```
<?php

/**
 * This file is part of the GeocoderLaravel library.
 *
 * (c) Antoine Corcy <contact@sbin.dk>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

use Ivory\HttpAdapter\CurlHttpAdapter;
use Ivory\HttpAdapter\Guzzle6HttpAdapter;
use Geocoder\Provider\Chain;
use Geocoder\Provider\BingMaps;
use Geocoder\Provider\FreeGeoIp;
use Geocoder\Provider\GoogleMaps;
use Geocoder\Provider\MaxMindBinary;

return [
    'providers' => [
        Chain::class => [
            GoogleMaps::class => [
                'en-AU',
                'Australia',
                true,
                env('GOOGLE_MAPS_API_KEY'),
            ],
            FreeGeoIp::class  => [],
        ],
        BingMaps::class => [
            'en-US',
            env('BING_MAPS_API_KEY'),
        ],
        GoogleMaps::class => [
            'en',
            'us',
            true,
            env('GOOGLE_MAPS_API_KEY'),
        ],
    ],
    'adapter'  => CurlHttpAdapter::class,
];
```

Yet when I run `$geocode = app('geocoder')->geocode('Los Angeles, CA')->get();` or any other address I am always getting the error:

> exception 'Geocoder\Exception\ChainNoResult' with message 'No provider could geocode address: "Los Angeles, CA".

Am I doing something wrong or is there a bug?

**Comment by j2r** [comment]
@jryd - I am facing the same issue. How did you fix that ?

**Comment by mikebronner** [comment]
It is likely that your configuration settings are wrong. Can you post them here?

**Comment by jryd** [comment]
@j2r it actually turned out that the configuration was fine for me - it was that I hadn't enabled the Geocoding API in my console.

I was using a key that I previously used for the Javascript API and completely forgot to check I had enabled to right API.

Perhaps double check that?
