### ISSUE TITLE
No provider could provide the coordinated 

### ISSUE THREAD

**Issue by IrfanS99** [geocoder-php/GeocoderLaravel#57]
Hi,

I am using your GeoCoder with version   "toin0u/geocoder-laravel" on laravel 5.2. I found an error: "No provider could provide the coordinated "  when I want to obtain an address using this code.
 try {
          $geocode = \Geocoder::reverse($request->input('latitude'), $request->input('longitude'))->toArray();
                } catch (\Exception $e) {
                    return $e->getMessage();
                }
Am I missing something? 

Thank you

**Comment by mikebronner** [comment]
The version for Laravel 5.2 is broken (at least I could never get it to work right). The new 1.0.0-RC version works for Laravel 5.3 and should fix previous issues. (Unfortunately it's not L5.2 compatible.)
