### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by IrfanS99** [geocoder-php/GeocoderLaravel#58]
Hi,

I found an issue 
![error](https://cloud.githubusercontent.com/assets/19969706/21036277/69ab6f06-bdf7-11e6-8f9e-a79fc4b90bad.png)

when I execute the installation command "composer require toin0u/geocoder-laravel:1.0.0-RC1@dev"

I already upgrade my Laravel to 5.3.26. Could you please solve my issue?

**Comment by mikebronner** [comment]
Hi @IrfanS99, it looks like your composer.json still requires some updates to the dev requirements. PHPUnit needs to have a version 5 or greater, and some other errors listed here. Make sure your require-dev matches the items listed here: https://github.com/laravel/laravel/blob/master/composer.json

Let me know if that helps (I'm pretty sure it will get you up and running). :)

**Comment by IrfanS99** [comment]
Thank you for your quick response, @mikebronner . I think I need your help again :D. I already followed your list. However, I found this error.

![error2](https://cloud.githubusercontent.com/assets/19969706/21036946/4fe5880e-bdfc-11e6-9a05-8edb6d43a89b.png)

I saw  willdurand/geocoder 3.3.x-dev requires php-http/client-implementation ^1.0 but when I execute 
"composer require php-http/client-implementation ^1.0"

This error appear, "The requested package php-http/client-implementation could not be found in any version, there may be a typo in the package name". Do I miss something?

**Comment by mikebronner** [comment]
Ah, thanks for this one. It looks like the dependencies got updated. I will take a look tomorrow

**Comment by mikebronner** [comment]
@IrfanS99 By any chance do you have your minimum stability set to dev in composer.json? Make sure that you have it set to stable, as well as the following:
```
    "config": {
        "preferred-install": "dist"
    }
```

**Comment by IrfanS99** [comment]
Thank you @mikebronner, it works :)

**Comment by IrfanS99** [comment]
Thank you @mikebronner, it works after I did:
 "composer remove"
"composer clear-cache"
"composer update"

**Comment by mikebronner** [comment]
Woot! :)
