### ISSUE TITLE
No provider could reverse coordinates

### ISSUE THREAD

**Issue by IrfanS99** [geocoder-php/GeocoderLaravel#60]
Hi @mikebronner ,

I found an error "No provider could reverse coordinates" when I do reverse using this code:
	try {
	$geocode = \Geocoder::reverse($request->input('latitude'), $request->input('longitude'))->toArray();
	} catch (\Exception $e) {
		return  $e->getMessage();
	}

I am already using "toin0u/geocoder-laravel": "1.0.0-RC1@dev" on Laravel 5.3. Do I need to config something else for reverse? Because currently I am using default config.

Regards

Irfan

**Comment by IrfanS99** [comment]
Okay, I have been trying in OSX (at first, I was on Windows OS). it gives me the result, when I am doing var_dump():
object(Geocoder\Model\AddressCollection)#605 (1) {
  ["addresses":"Geocoder\Model\AddressCollection":private]=>
  array(5) {
    [0]=>
    object(Geocoder\Model\Address)#569 (10) {
      ["coordinates":"Geocoder\Model\Address":private]=>
      object(Geocoder\Model\Coordinates)#570 (2) {
        ["latitude":"Geocoder\Model\Coordinates":private]=>
        float(-6.3243211)
        ["longitude":"Geocoder\Model\Coordinates":private]=>
        float(106.7990639)
      }
      ["bounds":"Geocoder\Model\Address":private]=>
      object(Geocoder\Model\Bounds)#571 (4) {
        ["south":"Geocoder\Model\Bounds":private]=>
        float(-6.3243211)
        ["west":"Geocoder\Model\Bounds":private]=>
        float(106.7990639)
        ["north":"Geocoder\Model\Bounds":private]=>
        float(-6.3243211)
        ["east":"Geocoder\Model\Bounds":private]=>
        float(106.7990639)
      }
      ["streetNumber":"Geocoder\Model\Address":private]=>
      string(2) "19"
      ["streetName":"Geocoder\Model\Address":private]=>
      string(17) "Jalan Rawa Kopi I"
      ["subLocality":"Geocoder\Model\Address":private]=>
      NULL
      ["locality":"Geocoder\Model\Address":private]=>
      NULL
      ["postalCode":"Geocoder\Model\Address":private]=>
      string(5) "16514"
      ["adminLevels":"Geocoder\Model\Address":private]=>
      object(Geocoder\Model\AdminLevelCollection)#572 (1) {
        ["adminLevels":"Geocoder\Model\AdminLevelCollection":private]=>
        array(4) {
          [1]=>
          object(Geocoder\Model\AdminLevel)#568 (3) {
            ["level":"Geocoder\Model\AdminLevel":private]=>
            int(1)
            ["name":"Geocoder\Model\AdminLevel":private]=>
            string(10) "Jawa Barat"
            ["code":"Geocoder\Model\AdminLevel":private]=>
            string(10) "Jawa Barat"
          }
          [2]=>
          object(Geocoder\Model\AdminLevel)#567 (3) {
            ["level":"Geocoder\Model\AdminLevel":private]=>
            int(2)
            ["name":"Geocoder\Model\AdminLevel":private]=>
            string(10) "Kota Depok"
            ["code":"Geocoder\Model\AdminLevel":private]=>
            string(10) "Kota Depok"
          }
          [3]=>
          object(Geocoder\Model\AdminLevel)#566 (3) {
            ["level":"Geocoder\Model\AdminLevel":private]=>
            int(3)
            ["name":"Geocoder\Model\AdminLevel":private]=>
            string(6) "Cinere"
            ["code":"Geocoder\Model\AdminLevel":private]=>
            string(6) "Cinere"
          }
          [4]=>
          object(Geocoder\Model\AdminLevel)#565 (3) {
            ["level":"Geocoder\Model\AdminLevel":private]=>
            int(4)
            ["name":"Geocoder\Model\AdminLevel":private]=>
            string(14) "Pangkalan Jati"
            ["code":"Geocoder\Model\AdminLevel":private]=>
            string(14) "Pangkalan Jati"
          }
        }
      }
      ["country":"Geocoder\Model\Address":private]=>
      object(Geocoder\Model\Country)#573 (2) {
        ["name":"Geocoder\Model\Country":private]=>
        string(9) "Indonesia"
        ["code":"Geocoder\Model\Country":private]=>
        string(2) "ID"
      }
      ["timezone":"Geocoder\Model\Address":private]=>
      NULL
    }
    [1]=>
    object(Geocoder\Model\Address)#576 (10) {
      ["coordinates":"Geocoder\Model\Address":private]=>
      object(Geocoder\Model\Coordinates)#577 (2) {
        ["latitude":"Geocoder\Model\Coordinates":private]=>
        float(-6.4024844)
        ["longitude":"Geocoder\Model\Coordinates":private]=>
        float(106.7942405)
      }
      ["bounds":"Geocoder\Model\Address":private]=>
      object(Geocoder\Model\Bounds)#578 (4) {
        ["south":"Geocoder\Model\Bounds":private]=>
        float(-6.461283)
        ["west":"Geocoder\Model\Bounds":private]=>
        float(106.716747)
        ["north":"Geocoder\Model\Bounds":private]=>
        float(-6.3144141)
        ["east":"Geocoder\Model\Bounds":private]=>
        float(106.918848)
      }
      ["streetNumber":"Geocoder\Model\Address":private]=>
      NULL
      ["streetName":"Geocoder\Model\Address":private]=>
      NULL
      ["subLocality":"Geocoder\Model\Address":private]=>
      NULL
      ["locality":"Geocoder\Model\Address":private]=>
      string(5) "Depok"
      ["postalCode":"Geocoder\Model\Address":private]=>
      NULL
      ["adminLevels":"Geocoder\Model\Address":private]=>
      object(Geocoder\Model\AdminLevelCollection)#579 (1) {
        ["adminLevels":"Geocoder\Model\AdminLevelCollection":private]=>
        array(2) {
          [1]=>
          object(Geocoder\Model\AdminLevel)#575 (3) {
            ["level":"Geocoder\Model\AdminLevel":private]=>
            int(1)
            ["name":"Geocoder\Model\AdminLevel":private]=>
            string(9) "West Java"
            ["code":"Geocoder\Model\AdminLevel":private]=>
            string(9) "West Java"
          }
          [2]=>
          object(Geocoder\Model\AdminLevel)#574 (3) {
            ["level":"Geocoder\Model\AdminLevel":private]=>
            int(2)
            ["name":"Geocoder\Model\AdminLevel":private]=>
            string(10) "Depok City"
            ["code":"Geocoder\Model\AdminLevel":private]=>
            string(10) "Depok City"
          }
        }
      }
      ["country":"Geocoder\Model\Address":private]=>
      object(Geocoder\Model\Country)#580 (2) {
        ["name":"Geocoder\Model\Country":private]=>
        string(9) "Indonesia"
        ["code":"Geocoder\Model\Country":private]=>
        string(2) "ID"
      }
      ["timezone":"Geocoder\Model\Address":private]=>
      NULL
    }
    [2]=>
    object(Geocoder\Model\Address)#585 (10) {
      ["coordinates":"Geocoder\Model\Address":private]=>
      object(Geocoder\Model\Coordinates)#586 (2) {
        ["latitude":"Geocoder\Model\Coordinates":private]=>
        float(-6.3219635)
        ["longitude":"Geocoder\Model\Coordinates":private]=>
        float(106.7898163)
      }
      ["bounds":"Geocoder\Model\Address":private]=>
      object(Geocoder\Model\Bounds)#587 (4) {
        ["south":"Geocoder\Model\Bounds":private]=>
        float(-6.3279799)
        ["west":"Geocoder\Model\Bounds":private]=>
        float(106.777725)
        ["north":"Geocoder\Model\Bounds":private]=>
        float(-6.314519)
        ["east":"Geocoder\Model\Bounds":private]=>
        float(106.7992601)
      }
      ["streetNumber":"Geocoder\Model\Address":private]=>
      NULL
      ["streetName":"Geocoder\Model\Address":private]=>
      NULL
      ["subLocality":"Geocoder\Model\Address":private]=>
      NULL
      ["locality":"Geocoder\Model\Address":private]=>
      NULL
      ["postalCode":"Geocoder\Model\Address":private]=>
      NULL
      ["adminLevels":"Geocoder\Model\Address":private]=>
      object(Geocoder\Model\AdminLevelCollection)#588 (1) {
        ["adminLevels":"Geocoder\Model\AdminLevelCollection":private]=>
        array(4) {
          [1]=>
          object(Geocoder\Model\AdminLevel)#584 (3) {
            ["level":"Geocoder\Model\AdminLevel":private]=>
            int(1)
            ["name":"Geocoder\Model\AdminLevel":private]=>
            string(9) "West Java"
            ["code":"Geocoder\Model\AdminLevel":private]=>
            string(9) "West Java"
          }
          [2]=>
          object(Geocoder\Model\AdminLevel)#583 (3) {
            ["level":"Geocoder\Model\AdminLevel":private]=>
            int(2)
            ["name":"Geocoder\Model\AdminLevel":private]=>
            string(10) "Depok City"
            ["code":"Geocoder\Model\AdminLevel":private]=>
            string(10) "Depok City"
          }
          [3]=>
          object(Geocoder\Model\AdminLevel)#582 (3) {
            ["level":"Geocoder\Model\AdminLevel":private]=>
            int(3)
            ["name":"Geocoder\Model\AdminLevel":private]=>
            string(6) "Cinere"
            ["code":"Geocoder\Model\AdminLevel":private]=>
            string(6) "Cinere"
          }
          [4]=>
          object(Geocoder\Model\AdminLevel)#581 (3) {
            ["level":"Geocoder\Model\AdminLevel":private]=>
            int(4)
            ["name":"Geocoder\Model\AdminLevel":private]=>
            string(14) "Pangkalan Jati"
            ["code":"Geocoder\Model\AdminLevel":private]=>
            string(14) "Pangkalan Jati"
          }
        }
      }
      ["country":"Geocoder\Model\Address":private]=>
      object(Geocoder\Model\Country)#589 (2) {
        ["name":"Geocoder\Model\Country":private]=>
        string(9) "Indonesia"
        ["code":"Geocoder\Model\Country":private]=>
        string(2) "ID"
      }
      ["timezone":"Geocoder\Model\Address":private]=>
      NULL
    }
    [3]=>
    object(Geocoder\Model\Address)#593 (10) {
      ["coordinates":"Geocoder\Model\Address":private]=>
      object(Geocoder\Model\Coordinates)#594 (2) {
        ["latitude":"Geocoder\Model\Coordinates":private]=>
        float(-6.3360895)
        ["longitude":"Geocoder\Model\Coordinates":private]=>
        float(106.7883416)
      }
      ["bounds":"Geocoder\Model\Address":private]=>
      object(Geocoder\Model\Bounds)#595 (4) {
        ["south":"Geocoder\Model\Bounds":private]=>
        float(-6.350388)
        ["west":"Geocoder\Model\Bounds":private]=>
        float(106.7723919)
        ["north":"Geocoder\Model\Bounds":private]=>
        float(-6.3144141)
        ["east":"Geocoder\Model\Bounds":private]=>
        float(106.809174)
      }
      ["streetNumber":"Geocoder\Model\Address":private]=>
      NULL
      ["streetName":"Geocoder\Model\Address":private]=>
      NULL
      ["subLocality":"Geocoder\Model\Address":private]=>
      NULL
      ["locality":"Geocoder\Model\Address":private]=>
      NULL
      ["postalCode":"Geocoder\Model\Address":private]=>
      NULL
      ["adminLevels":"Geocoder\Model\Address":private]=>
      object(Geocoder\Model\AdminLevelCollection)#596 (1) {
        ["adminLevels":"Geocoder\Model\AdminLevelCollection":private]=>
        array(3) {
          [1]=>
          object(Geocoder\Model\AdminLevel)#592 (3) {
            ["level":"Geocoder\Model\AdminLevel":private]=>
            int(1)
            ["name":"Geocoder\Model\AdminLevel":private]=>
            string(9) "West Java"
            ["code":"Geocoder\Model\AdminLevel":private]=>
            string(9) "West Java"
          }
          [2]=>
          object(Geocoder\Model\AdminLevel)#591 (3) {
            ["level":"Geocoder\Model\AdminLevel":private]=>
            int(2)
            ["name":"Geocoder\Model\AdminLevel":private]=>
            string(10) "Depok City"
            ["code":"Geocoder\Model\AdminLevel":private]=>
            string(10) "Depok City"
          }
          [3]=>
          object(Geocoder\Model\AdminLevel)#590 (3) {
            ["level":"Geocoder\Model\AdminLevel":private]=>
            int(3)
            ["name":"Geocoder\Model\AdminLevel":private]=>
            string(6) "Cinere"
            ["code":"Geocoder\Model\AdminLevel":private]=>
            string(6) "Cinere"
          }
        }
      }
      ["country":"Geocoder\Model\Address":private]=>
      object(Geocoder\Model\Country)#597 (2) {
        ["name":"Geocoder\Model\Country":private]=>
        string(9) "Indonesia"
        ["code":"Geocoder\Model\Country":private]=>
        string(2) "ID"
      }
      ["timezone":"Geocoder\Model\Address":private]=>
      NULL
    }
    [4]=>
    object(Geocoder\Model\Address)#600 (10) {
      ["coordinates":"Geocoder\Model\Address":private]=>
      object(Geocoder\Model\Coordinates)#601 (2) {
        ["latitude":"Geocoder\Model\Coordinates":private]=>
        float(-6.3360895)
        ["longitude":"Geocoder\Model\Coordinates":private]=>
        float(106.7883416)
      }
      ["bounds":"Geocoder\Model\Address":private]=>
      object(Geocoder\Model\Bounds)#602 (4) {
        ["south":"Geocoder\Model\Bounds":private]=>
        float(-6.3849575)
        ["west":"Geocoder\Model\Bounds":private]=>
        float(106.7634615)
        ["north":"Geocoder\Model\Bounds":private]=>
        float(-6.3139448)
        ["east":"Geocoder\Model\Bounds":private]=>
        float(106.80941)
      }
      ["streetNumber":"Geocoder\Model\Address":private]=>
      NULL
      ["streetName":"Geocoder\Model\Address":private]=>
      NULL
      ["subLocality":"Geocoder\Model\Address":private]=>
      NULL
      ["locality":"Geocoder\Model\Address":private]=>
      NULL
      ["postalCode":"Geocoder\Model\Address":private]=>
      string(5) "16514"
      ["adminLevels":"Geocoder\Model\Address":private]=>
      object(Geocoder\Model\AdminLevelCollection)#603 (1) {
        ["adminLevels":"Geocoder\Model\AdminLevelCollection":private]=>
        array(2) {
          [1]=>
          object(Geocoder\Model\AdminLevel)#599 (3) {
            ["level":"Geocoder\Model\AdminLevel":private]=>
            int(1)
            ["name":"Geocoder\Model\AdminLevel":private]=>
            string(9) "West Java"
            ["code":"Geocoder\Model\AdminLevel":private]=>
            string(9) "West Java"
          }
          [2]=>
          object(Geocoder\Model\AdminLevel)#598 (3) {
            ["level":"Geocoder\Model\AdminLevel":private]=>
            int(2)
            ["name":"Geocoder\Model\AdminLevel":private]=>
            string(10) "Depok City"
            ["code":"Geocoder\Model\AdminLevel":private]=>
            string(10) "Depok City"
          }
        }
      }
      ["country":"Geocoder\Model\Address":private]=>
      object(Geocoder\Model\Country)#604 (2) {
        ["name":"Geocoder\Model\Country":private]=>
        string(9) "Indonesia"
        ["code":"Geocoder\Model\Country":private]=>
        string(2) "ID"
      }
      ["timezone":"Geocoder\Model\Address":private]=>
      NULL
    }
  }
}
{"message":"Bad Request","status_code":400}
However, I am still working to retrieve the country using getCountry() method because there is an error ""Call to undefined method Geocoder\\Model\\AddressCollection::getCountry()"". I have seen there are method getCountry() but it is in Address.php model. so How do I call the method?

**Comment by mikebronner** [comment]
Hi @IrfanS99, are you using Homestead or Valet? macOS has an old version of OpenSSL installed, which causes problems with curl requests to https URLs. To get around this, you need to run the code in Homestead, or update OpenSSL on your Mac. See #64 . Let me know how you get on.

Thanks! :)
