### ISSUE TITLE
Error: No provider could geocode address:

### ISSUE THREAD

**Issue by ng111w** [geocoder-php/GeocoderLaravel#62]
Hi, 
On installing this package unto my laravel 5.2 project with php 5.5.9, I kept getting the error below:
**No provider could geocode address:**

I did some debugging including printing out the url path, and checking it from the browser.
https://maps.googleapis.com/maps/api/geocode/json?address=se186tl&language=en%C2%AEion=uk&key=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
The absolute path return expected address from the browser. 

However I notice that within the GoogleMap Class located in the Willdurand folder (package), this line: **$content = (string) $this->getAdapter()->get($query)->getBody();** within the **executeQuery($query)** function does not return anything.

This seem to be the beginning of the issue, and I've not been able to work it out.

Can anyone help and is anyone getting the same problem ?

Maybe I am doing something wrong.

Many Thanks in advance

**Comment by ng111w** [comment]
Just to add to the above, the error is coming from the file mentioned below.
ChainNoResult in Chain.php line 56:

**Comment by byhbt** [comment]
I have same issue and I think maybe the answer here, hope it help.
https://github.com/geocoder-php/GeocoderLaravel/issues/57

**Comment by mikebronner** [comment]
Yea, sorry guys. Right now not 5.2 compatible. Closing for now. Please let me know if you have the same issues using 5.3.

**Comment by ng111w** [comment]
Hi @mikebronner , thank you for your reply.
After installing laravel 5.3 and updated details as required, the error still persists.
See set-up below

"require": {
        "php": ">=5.6.4",
        "laravel/framework": "5.3.*",
        "toin0u/geocoder-laravel": "1.0.0-RC1@dev"
    },

Any help will be appreciated
