### ISSUE TITLE
Does not work with Laravel 5.4

### ISSUE THREAD

**Issue by dominicmomentum** [geocoder-php/GeocoderLaravel#63]
Version 0.6.0

Got this exception
FatalThrowableError: Call to undefined method Illuminate\Foundation\Application::share()

in that file /vendor/toin0u/geocoder-laravel/src/GeocoderServiceProvider.php:72

We need to refactor the Provider in order to use singleton instead of share as described in the upgrade documentation for Laravel 5.4

**Comment by ChrisReid** [comment]
I have fixed this. Just a couple of amends in the service provider. I'll issue a pull request now

**Comment by azcoppen** [comment]
+1

**Comment by mikebronner** [comment]
Thanks, will look into this tomorrow, been traveling all of last week. :) Thanks for opening the issue :)

**Comment by mikebronner** [comment]
Ah, ok, I see now. Version 0.6.0 is no longer supported. Please upgrade to 1.0.0-RC. I went through and installed it in L5.4 just now, and tests are still passing. Please re-open if you still have issues after updating to the RC version. Thanks :)
