### ISSUE TITLE
Error with Laravel 5.4

### ISSUE THREAD

**Issue by paguemaou** [geocoder-php/GeocoderLaravel#66]
Hi,
I'm upgrading a L5.1 app with "toin0u/geocoder-laravel": "0.6.0"

Now, I use a fresh new Lavel 5.4.

The first composer update with "toin0u/geocoder-laravel": "^1.0", in composer.json is OK.

I also use Barryvdh ide-helper. So, I have in composer.json 
```javascript 
"post-update-cmd": [
            "Illuminate\\Foundation\\ComposerScripts::postUpdate",
            "php artisan ide-helper:generate",
            "php artisan ide-helper:meta",
            "php artisan optimize"
        ]
```
If I add in app.php Geocoder\Laravel\Providers\GeocoderService::class, I have this error during the next composer update
```javascript
$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files
> Illuminate\Foundation\ComposerScripts::postUpdate
> php artisan ide-helper:generate
  [Symfony\Component\Debug\Exception\FatalThrowableError]
  Class 'Geocoder\HttpAdapter\CurlHttpAdapter' not found
Script php artisan ide-helper:generate handling the post-update-cmd event returned with error code 1
```
Last point, composer update works well if I remove the ide-helper steps in composer.json
```javascript 
"post-update-cmd": [
            "Illuminate\\Foundation\\ComposerScripts::postUpdate",
            "php artisan optimize"
        ]
```
What do you think ? 
Is it coming from Geocoder (maybe not validated with L5.4?) or does this comes from barryvdh/ide-helper ?

Thanks in advance,
Paguemaou

**Comment by mikebronner** [comment]
Hi @paguemaou, the config file and available providers changed a lot from 0.6 to 1.0. Did you upgrade your configuration and providers as well? That's my initial guess that your settings are still set for the old version. See the readme for the format of the config file, and there's also a link to the available providers and adapters.

Let me know if that was the case.

Thanks!
~Mike

**Comment by paguemaou** [comment]
Thanks for your reply @mikebronner.

I use a fresh Laravel 5.4 install.

I just do 

1) add "toin0u/geocoder-laravel": "^1.0" in composer.json
2) composer update (OK....)
3) add Geocoder\Laravel\Providers\GeocoderService::class in app.php
4) composer update => error in Barryvdh ide-helper
```php
post-update-cmd": [
            "Illuminate\\Foundation\\ComposerScripts::postUpdate",
            "php artisan ide-helper:generate",           **=> error during this step**
            "php artisan ide-helper:meta",
            "php artisan optimize"
        ]
```
Thanks for you help

Paguemaou

**Comment by mikebronner** [comment]
I'm not sure on this one ... I will have to put this on hold for the moment until I can test it out.

**Comment by zedentox** [comment]
My configuration :
- laravel/framework 5.4.13
- barryvdh/laravel-ide-helper 2.3.2
- willdurand/geocoder 3.3.0
- toin0u/geocoder-laravel 1.0.1

`php artisan ide-helper:generate` is OK for me.

**Comment by paguemaou** [comment]
From composer info, I have the same versions as you.

I go on holidays for one week. I'll try with only these librairies.

Thanks for your help, see you next week !

**Comment by paguemaou** [comment]
Yepee ! 
I've previously installed an old version of "toin0u/geocoder-laravel" 
I also do 
```javascript
php artisan vendor:publish
```
Later, I've done a composer update with the latest version of "toin0u/geocoder-laravel" but I haven't delete the old config/geocoder.php file before the next composer update.

This was the bug's origin !

Thanks for your help @zedentox  (maintenant, je pars dans les Pyrennées !)

**Comment by zedentox** [comment]
@paguemaou Bon voyage ! 🇫🇷 

@mikebronner This issue can be closed 😎

**Comment by mikebronner** [comment]
Awesome! Thanks @zedentox for the helping hand. :)

**Comment by sameer1202** [comment]
hi @paguemaou @mikebronner @zedentox  
I have also removed the config/geocoder.php configuration file ,still Getting the error message .
Error message when I do composer install or update I get the error
```
Nothing to install or update
Package egeloen/http-adapter is abandoned, you should avoid using it. Use php-http/httplug instead.

Generating autoload files
> Illuminate\Foundation\ComposerScripts::postInstall
> php artisan optimize
                                                 
  [Symfony\Component\Debug\Exception\FatalThrowableError]    
  Class 'Toin0u\Geocoder\GeocoderServiceProvider' not found  

```
In composer.json I have added "toin0u/geocoder-laravel": "^1.0",
There is no Geocoder alias in the aliases section of the config/app.php.
have added Geocoder\Laravel\Providers\GeocoderService::class, in config/app.php . but still getting the above error .
my composer.json file looks like this
```
{
    "name": "laravel/laravel",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "type": "project",
    "minimum-stability": "dev",
    "prefer-stable": true,

    "require": {
        "php": ">=5.6.4",
        "toin0u/geocoder-laravel": "^1.0",
        //"toin0u/geocoder-laravel": "@stable",
        "laravel/framework": "5.4.*",
        "illuminate/support": "5.4.x",
        "illuminate/console": "5.4.x",
        "symfony/process": "~3.2",
        "barryvdh/laravel-async-queue": "0.6.x",
        "laravelcollective/html": "5.4.x-dev"
    },
    "require-dev": {
        "fzaninotto/faker": "~1.4",
        "mockery/mockery": "0.9.*",
        "phpunit/phpunit": "~5.7",
        "symfony/css-selector": "3.1.*",
        "symfony/dom-crawler": "3.1.*",
        "barryvdh/laravel-debugbar": "^2.1"
    },
    "autoload": {
        "classmap": [
            "database",
            "app/Models",
            "database/migrations",
            "database/seeds",
            "app/libraries"
        ],
    "psr-4": {
            "App\\": "app/"
        }
    },

     "extra": {
        "branch-alias": {
            "dev-master": "0.6-dev"
        }
    },

    "autoload-dev": {
        "classmap": [
            "tests/TestCase.php"
        ]
    },
    "scripts": {
        "post-root-package-install": [
            "php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "php artisan key:generate"
        ],
        "post-install-cmd": [
            "Illuminate\\Foundation\\ComposerScripts::postInstall",
            "php artisan optimize"
        ],
        "post-update-cmd": [
            "Illuminate\\Foundation\\ComposerScripts::postUpdate",
            "php artisan ide-helper:generate", 
            "php artisan ide-helper:meta",
            "php artisan optimize"
        ]
    },
    "config": {
        "preferred-install": "dist"
    }
}
```
Please help.Thanku
