### ISSUE TITLE
bump egeloen/http-adapter version

### ISSUE THREAD

**Issue by danijelk** [geocoder-php/GeocoderLaravel#70]
Hi,

  Problem 1
    - Installation request for egeloen/http-adapter (locked at 1.0.2) -> satisfiable by egeloen/http-adapter[1.0.2].
    - toin0u/geocoder-laravel 1.0.0 requires willdurand/geocoder ~3.3 -> satisfiable by willdurand/geocoder[v3.3.0].
    - toin0u/geocoder-laravel 1.0.1 requires willdurand/geocoder ~3.3 -> satisfiable by willdurand/geocoder[v3.3.0].
    - toin0u/geocoder-laravel 1.0.2 requires willdurand/geocoder ~3.3 -> satisfiable by willdurand/geocoder[v3.3.0].
    - toin0u/geocoder-laravel 1.0.3 requires willdurand/geocoder ~3.3 -> satisfiable by willdurand/geocoder[v3.3.0].
    - willdurand/geocoder v3.3.0 requires egeloen/http-adapter ~0.8 -> satisfiable by egeloen/http-adapter[0.8.0].
    - Conclusion: don't install egeloen/http-adapter 0.8.0
    - Installation request for toin0u/geocoder-laravel ^1.0 -> satisfiable by toin0u/geocoder-laravel[1.0.0, 1.0.1, 1.0.2, 1.0.3].

We're not able to install 0.8 cause of other updated libs, would it be possible to make the jump to ^1.0? Or even better jump on the new php-http/httplug train instead of the deprecated egeloen/http-adapter?

**Comment by mikebronner** [comment]
Not at this time ... this is an issue with the geocoderphp package and should be raised there. Even if I fixed the dependency to the new package, Will's geocoderphp package would still pull in the egeloen package, thus still making it impossible for you to install.
