### ISSUE TITLE
PHPDoc is wrong on \Geocoder\Laravel\ProviderAndDumperAggregator::get

### ISSUE THREAD

**Issue by Alexgmin** [geocoder-php/GeocoderLaravel#78]
### Issue Description
![image](https://cloud.githubusercontent.com/assets/8340441/25989672/583f4c68-36fd-11e7-9ecf-dfd449dbd0c1.png)

Also, instead of 
```
    /**
     * @var AddressCollection
     */
```
it should be
```
    /**
     * @var \Geocoder\Model\AddressCollection
     */
```
![image](https://cloud.githubusercontent.com/assets/8340441/25989779/c0aba012-36fd-11e7-8082-5559b43e0ac0.png)

![image](https://cloud.githubusercontent.com/assets/8340441/25989771/b8474f52-36fd-11e7-8191-8a06f6716212.png)

**Comment by Nyholm** [comment]
You are correct, that is missing. 

We should add `use Geocoder\Model\AddressCollection;` at the top of the file. Could you add a PR?

**Comment by Alexgmin** [comment]
I'll have to setup the project at home, and also, this would be my first PR, but sure.

**Comment by Nyholm** [comment]
That would be great. Im looking forward to review it.

**Comment by mikebronner** [comment]
@Alexgmin Thanks for reporting that. Should be fixed now. Let us know if you find anything else. :)

**Comment by mikebronner** [comment]
@Nyholm thanks for responding so quickly to the issue. :) (Small things like this I don't mind fixing without PRs.)
