### ISSUE TITLE
Prepare for 4.0 update of the Geocoder

### ISSUE THREAD

**Issue by Nyholm** [geocoder-php/GeocoderLaravel#81]
The willdurand/geocoder is about to release 4.0 in 2 months. There is quite a lot of changes but the migration should be smooth. The major changes are: 

* Some changes in the interfaces for `Provider` and `Geocoder`
* Introduce a `GeocodeQuery` object
* Use of HTTPlug
* Each provider is in its own package. 

The API is pretty stable and it will not be any more major changes as I see it. Im not sure how many of these changes that will effect the users of the Laravel package.

**Comment by mikebronner** [comment]
Thanks @Nyholm! Been looking forward to the HTTPlug one for a while. I will start a new branch in preparation over the coming weeks.

**Comment by Nyholm** [comment]
I just tagged some beta versions. If nobody complains the betas will be stable versions within 4-6 weeks.

**Comment by mikebronner** [comment]
@Nyholm Woot! I'll start working on that this weekend, thanks :)

**Comment by mikebronner** [comment]
@Nyholm Quick question: For some reason I can't figure out how to pull in dev-master for the geocoder package. It always falls back to the latest release (3.3.0). I have tried the following in my composer.json:

```
        "willdurand/geocoder": "4.0-dev@dev"
        "willdurand/geocoder": "4.0@dev"
        "willdurand/geocoder": "4.0-dev"
        "willdurand/geocoder": "dev-master"
```

Any suggestions? Thanks!

**Comment by mikebronner** [comment]
@Nyholm Got this in place now .... tests are all green. Added in commit b38a86d8. Keeping this open until 4.0 goes live to make sure it passes.

**Comment by Nyholm** [comment]
Cool. Good job. Im happy the update will be quite smooth for the users.

**Comment by mikebronner** [comment]
Added more tests, and did some more refactoring. Code coverage now at 96%.
