### ISSUE TITLE
Coveralls Not Showing Source

### ISSUE THREAD

**Issue by mikebronner** [geocoder-php/GeocoderLaravel#88]
Hi @willdurand, would you mind re-authorizing coveralls for this repo? That way it can show the source code in the coverage analysis. Thanks! :)

This is the message Coveralls is showing:
```
SOURCE NOT AVAILABLE
The owner of this repo needs to re-authorize with github; their OAuth credentials are no longer valid so the file cannot be pulled from the github API.
```

**Comment by willdurand** [comment]
How do I do that? :p

**Comment by willdurand** [comment]
poke @toin0u  I guess

**Comment by mikebronner** [comment]
@willdurand, i thought maybe you had set it up. Do you control the travis build for this repo? Maybe we should go ahead and migrate them over to ones that you do control?

**Comment by Nyholm** [comment]
I've started to use Scrutinizer for most repos in this org. I've actually set it up to run after you push to master here. You just need to add a line to travis.yml. See https://github.com/geocoder-php/geoip2-provider/blob/master/.travis.yml#L13-L15

Btw, I've checked Coveralls now. It looks like it is enabled. I clicked "repair" and it looks good. Where do you see the error message?

**Comment by mikebronner** [comment]
See here: https://coveralls.io/builds/12122868/source?filename=src%2FProviders%2FGeocoderService.php

**Comment by Nyholm** [comment]
Here is the link: https://scrutinizer-ci.com/g/geocoder-php/GeocoderLaravel/

Here is the markdown :
```
[![Code Coverage](https://scrutinizer-ci.com/g/geocoder-php/GeocoderLaravel/badges/coverage.png?b=master)](https://scrutinizer-ci.com/g/geocoder-php/GeocoderLaravel/?branch=master)
```

---------

Btw, this is what I see on your link: 

![print](https://user-images.githubusercontent.com/1275206/27518355-6006a8b6-59de-11e7-9111-9c97fd28ead5.png)

**Comment by mikebronner** [comment]
wow, interesting, here is what I see: 
![screen shot 2017-06-25 at 10 46 10 am](https://user-images.githubusercontent.com/1791050/27518381-9011a916-5993-11e7-81f4-12086c1e249a.png)

Do you see the code if you log out of coveralls?

**Comment by mikebronner** [comment]
Thanks for the scrutinizer info ... badge and link added

**Comment by mikebronner** [comment]
@Nyholm can you give me co-maintainer (or something to that affect) access to this repo in scrutinizer, if thats OK? I would like to address some false positives in the analysis and be able to make adjustments to build reports as they happen.

**Comment by Nyholm** [comment]
Of course. 

I just learned that Scrutinizer syncs with Github. Last sync 2hours ago. You membership to this organization is marked "private". See here: https://github.com/orgs/geocoder-php/people
Try making it public and you will (probably) have access. 

I think it is strange that if you login with Github on Scrutinizer that you do not have access.. Also, I cant override the team settings somehow... It really has to sync with Github. 

Maybe @schmittjoh wants a friendly ping here.

**Comment by mikebronner** [comment]
So, it looks like it only shows the code if you authorize github. I was expecting it to show the code publicly, since this is a public repo. Odd. /shrug

I think we're all sorted now, thanks for your help @Nyholm. :)

**Comment by schmittjoh** [comment]
@mikebronner, even with private membership, Scrutinizer should be able to sync your membership, but I think you might not have had an account on Scrutinizer yet? 

Without an account, you should still be able to see a public repository, but you cannot make changes to it. Let me know if I missed anything.

**Comment by mikebronner** [comment]
@schmittjoh Thanks for jumping in ... I think the trick was that I had to add the repo to my scrutinizer account (which I hadn't, I assumed that the owner would manage who has access to it from their end). After adding the repo to my Scrutinizer account, I was able to adjust the settings. Thanks! :)
