### ISSUE TITLE
Error handling - if address returns no results, geocode call throws error

### ISSUE THREAD

**Issue by matthewpennell** [geocoder-php/GeocoderLaravel#89]
### General Information
GeocoderLaravel Version: ^1.0
Laravel Version: 5.4
PHP Version: 7
Operating System and Version: OSX 10.12.5

### Issue Description
When passing invalid data to the Geocoder, it throws an uncatchable error, even with debug set to false.

### Steps to Replicate
I submit an invalid string via a form. The geocode call fails and triggers the Laravel stacktrace page. Adding additional levels of checking doesn't seem to make any difference. Switching off Laravel debugging doesn't work (still get an error page, with no stacktrace). I just want it to fail gracefully.

    try {
        $result = json_decode(Geocoder::geocode($request->city . ',' . $request->country)->dump('geojson'));
        $first_match = json_decode($result[0]);
    } catch (Exception $e) {
        // Write the error to the Laravel log.
        Log::info('Failed to successfully geocode address "' . $request->city . ',' . $request->country . '"');
    }

### Stack Trace
No provider could geocode address: "asd,Afghanistan".
in Chain.php (line 56)
at Chain->geocode('asd,Afghanistan')
in ProviderAggregator.php (line 59)
at ProviderAggregator->geocode('asd,Afghanistan')
in ProviderAndDumperAggregator.php (line 77)
at ProviderAndDumperAggregator->geocode('asd,Afghanistan')
in Facade.php (line 221)
at Facade::__callStatic('geocode', array('asd,Afghanistan'))
in CompanyController.php (line 97)
at CompanyController->store(object(Request))

**Comment by mikebronner** [comment]
@matthewpennell  Thanks for submitting this issue. Can you provide the invalid address you are trying to geocode, so I can reproduce? Thanks!

**Comment by mikebronner** [comment]
To catch this, you will have to implement it as follows:

```php
        try {
            app('geocoder')
                ->geocode('asd,Afghanistan')
                ->get();
        } catch (\Geocoder\Exception\ChainNoResult $exception) {
            //
        }
```

The reason here is that the ChainNoResult does not Extend from the \Extension class. I will open an issue or PR for that in the parent repo.

Let me know if this works for you.

**Comment by mikebronner** [comment]
Updated the catch parameters above to \Throwable. That should catch everything. I think that's the preferred way moving forward.

**Comment by matthewpennell** [comment]
Thanks for the fast response - I'll try your solution and get back to you.

**Comment by matthewpennell** [comment]
Yes, that works, thanks a lot!

**Comment by mikebronner** [comment]
Awesome, glad its working! :) On a side note: the upcoming version 2.0 will not throw an exception, but just return an empty result.

**Comment by matthewpennell** [comment]
Nice. I tried updating to 2.0 in case that fixed it, but the @dev flag started a cascade of composer dependencies of other `dev` releases so I gave up and came here instead. :)
