### ISSUE TITLE
No provider could geocode address

### ISSUE THREAD

**Issue by mrkalmdn** [geocoder-php/GeocoderLaravel#90]
### General Information
GeocoderLaravel Version: 1.1
Laravel Version: 5.4.27
PHP Version: 7.0.10
Operating System and Version: Windows 7

### Issue Description
ChainNoResult
No provider could geocode address: "Los Angeles, CA".

### Steps to Replicate
Followed installation instruction
1. Install the package
```
composer require toin0u/geocoder-laravel
```
2. Register the Geocoder
```
// 'providers' => [
   Geocoder\Laravel\Providers\GeocoderService::class,
// ];
```
3. Added Google Map API in .env
4. dd in web.php
```
Route::get('/', function () {
    dd(app('geocoder')->geocode('Los Angeles, CA')->get());
});
```

**Comment by mikebronner** [comment]
This is most likely a configuration issue. Also, please update your package to version 1.1.1.
I tested your code and get results back using the 1.1.1 version.

If you have a `geocoder.php` config file, please delete it and try the one that came with the package.

Are you running this in homestead? If not, try that. This error would happen on older versions of OpenSSL on the mac (when not using Homestead), guessing there might be some issues with that on Windows as well.

**Comment by mrkalmdn** [comment]
Thank you for your response @mikebronner.

Followed your instruction but I'm still getting the same issue with Laragon v2.1.0. Homestead works, though. Thanks!

**Comment by mikebronner** [comment]
Thanks for the update. Yea, I have never used Laragon. It's most likely that it does not have the most up-to-date OpenSSL packages installed.

**Comment by mrkalmdn** [comment]
For those who will encounter this issue using Windows and Laragon, you need to environment variable.

```
set OPENSSL_CONF=C:\laragon\bin\apache\apache-version-of-your-apache\conf\openssl.cnf
```

**Comment by mikebronner** [comment]
Awesome @mrkalmdn, thanks for following up with the fix!! :)
