### ISSUE TITLE
Geocoder 4.0 Release Prep Tasks

### ISSUE THREAD

**Issue by mikebronner** [geocoder-php/GeocoderLaravel#93]
- [x] Update readme with detailed instructions for changes in 4.0.
- [x] Update config with minimum setup, and provide examples in documentation instead, in order to reduce package dependencies.
- [x] Update composer.json with appropriate versions of dependent packages.
- [x] Update composer.json with appropriate minimum-stability.

**Comment by Nyholm** [comment]
As you probably noticed. I released version 4.0.0 a few days ago.

**Comment by mikebronner** [comment]
@Nyholm Thanks! Will get it out this weekend. Been swamped over the last two weeks. :)

**Comment by Nyholm** [comment]
No rush. I just wanted you to know. 

//Tobias Nyholm

Skickat på språng

**Comment by mikebronner** [comment]
@Nyholm I am unable to get any of the IP geocoders to work with the release version. Any thoughts on what might cause this?

**Comment by mikebronner** [comment]
Released as version 4.0.0 to maintain major version parity with the parent package.

**Comment by Nyholm** [comment]
Wohoo!
