### ISSUE TITLE
Composer throwing error with Laravel 5.4

### ISSUE THREAD

**Issue by foziazahoor** [geocoder-php/GeocoderLaravel#95]
### General Information
GeocoderLaravel Version: ^4.0
Laravel Version: 5.4
PHP Version: PHP 7.1.8-1+ubuntu14.04.1+deb.sury.org+1 (cli)
Operating System and Version: ubuntu 14.04 LTS

Composer throwing error:

$ composer require toin0u/geocoder-laravel
Using version ^4.0 for toin0u/geocoder-laravel
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - geocoder-php/common-http 4.0.0 requires psr/http-message-implementation ^1.0 -> no matching package found.
    - toin0u/geocoder-laravel 4.0.0 requires geocoder-php/google-maps-provider ^4.0 -> satisfiable by geocoder-php/google-maps-provider[4.0.0].
    - geocoder-php/google-maps-provider 4.0.0 requires geocoder-php/common-http ^4.0 -> satisfiable by geocoder-php/common-http[4.0.0].
    - Installation request for toin0u/geocoder-laravel ^4.0 -> satisfiable by toin0u/geocoder-laravel[4.0.0].

Installed fresh installation of laravel 5.4 didn't installed any package other than GeocoderLaravel

**Comment by Nyholm** [comment]
Try installing guzzlehttp/psr before

//Tobias Nyholm

**Comment by mikebronner** [comment]
@foziazahoor Looking into this now, trying to reproduce. Will check back in shortly with an update

**Comment by mikebronner** [comment]
@Nyholm It appears to be the following requirement in common-http:
`"psr/http-message-implementation": "^1.0"`. That package is not resolvable by composer. Any thoughts?

**Comment by mikebronner** [comment]
@foziazahoor Please give 4.0.1 a shot. I added the missing dependency. Let me know if it works.

Thanks for reporting this! :)

**Comment by Nyholm** [comment]
Guzzle's psr package has no conflict issues. It is only their http client. 

Yeah, it's quite a few packages with similar names. I'll try to clear it out:

Psr/message: interfaces for http message
Psr/http-message-implementation: virtual package that require you to install any psr implementation (example guzzlehttp/psr7)
Php-http/message: includes message factories to create requests and responses.

**Comment by mikebronner** [comment]
Awesome, thanks for clearing that up for me.

**Comment by foziazahoor** [comment]
@Nyholm  & @mikebronner  thank you so much!

after installing guzzlehttp/psr it is working fine!

**Comment by mikebronner** [comment]
Awesome, great to hear it! :)
