### ISSUE TITLE
How to get State from response?

### ISSUE THREAD

**Issue by foziazahoor** [geocoder-php/GeocoderLaravel#97]
How to get state from response?

**Comment by mikebronner** [comment]
I have added some tests to illustrate how to do this. For future reference, these types of questions are best asked in the parent project, as GeocoderLaravel is a wrapper for it, and doesn't actually alter the internal functionality of the geocoding process.

https://github.com/geocoder-php/GeocoderLaravel/blob/7ab7d2c21bdb68af13baae96fced333adaa11ecb/tests/Laravel5_3/Providers/GeocoderServiceTest.php#L282-L294

Fixes #98

**Comment by foziazahoor** [comment]
Thank you so much @mikebronner
